#!/bin/bash

# argument 1 is the host
# argument 2 is the port
# argument 3 is the database service's name

for i in {1..20}; do
	if mysqladmin ping -h0.0.0.0 -P "$2"  -u root --silent; then
		echo "$3 is alive"
		exit 0
	fi

	echo "$3 is not alive, will try again"
	sleep 2
done

echo "$3 is not alive"
cat "$4"
exit 2
