#!/bin/sh

# argument 1 is the string need grep
# argument 2 is the filename

set -eu
OUT_DIR=/tmp/tidb_binlog_test

if grep -Fq "$1" "$2"; then
    echo "TEST FAILED: '$2' CONTAIN '$1'"
    echo "____________________________________"
    cat "$2"
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
    exit 1
fi