#!/bin/bash

set -eu
OUT_DIR=/tmp/tidb_cdc_test

if ! grep -Eq "$1" "$OUT_DIR/sql_res.$TEST_NAME.txt"; then
    echo "TEST FAILED: OUTPUT DOES NOT CONTAIN '$1'"
    echo "____________________________________"
    cat "$OUT_DIR/sql_res.$TEST_NAME.txt"
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
    exit 1
fi
