#!/bin/sh
# parameter 1: sql
# parameter 2: database host
# parameter 3: database port
# parameter 4: other mysql client settings

set -e

sql=${1}
shift
host=${1:-127.0.0.1}
shift
port=${1:-4000}
shift
other=${*}

echo "[$(date)] Executing SQL: ${sql}" > "$OUT_DIR/sql_res.$TEST_NAME.txt"
mysql -uroot -h${host} -P${port} ${other} --default-character-set utf8mb4 -E -e "${sql}" > "$OUT_DIR/sql_res.$TEST_NAME.txt"
