#!/bin/bash

# --workdir: work directory
# --binary: path to cdc test binary
# --logsuffix: log suffix
# --statusaddr: status address

set -e

workdir=
binary=
logsuffix=
statusaddr=
pwd=$pwd

while [[ ${1} ]]; do
    case "${1}" in
        --workdir)
            workdir=${2}
            shift
            ;;
        --binary)
            binary=${2}
            shift
            ;;
        --logsuffix)
            logsuffix=${2}
            shift
            ;;
        --statusaddr)
            statusaddr="--status-addr ${2}"
            shift
            ;;
        *)
            echo "Unknown parameter: ${1}" >&2
            return 1
    esac

    if ! shift; then
        echo 'Missing parameter argument.' >&2
        return 1
    fi
done

echo "[$(date)] <<<<<< START cdc server in $TEST_NAME case >>>>>>"
cd $workdir
pid=$(ps -C run_cdc_server -o pid=)
$binary -test.coverprofile="$OUT_DIR/cov.$TEST_NAME_$pid.out" server --log-file $workdir/cdc$logsuffix.log --log-level info $statusaddr >> $workdir/stdout$logsuffix.log 2>&1 &
cd $pwd
