#!/bin/bash

# parameter 1: work directory
# parameter 2: path to cdc test binary
# parameter 3: pd addr

set -e

workdir=$1
binary=$2
pd=$3
pwd=$pwd
TLS_DIR=$workdir/tls

echo "[$(date)] <<<<<< START cdc server in $TEST_NAME case >>>>>>"
cd $workdir
$binary -test.coverprofile="$OUT_DIR/cov.$TEST_NAME.out" server \
    --log-file=$workdir/cdc.log --log-level=info \
    --pd=$pd \
    --ca=$TLS_DIR/ca.pem --cert=$TLS_DIR/cdc.pem --key=$TLS_DIR/cdc.key \
    >> $workdir/stdout.log 2>&1 &
cd $pwd
