#!/bin/bash

# --workdir: work directory
# --tidb-config: path to tidb config file
# --retry: retry times

set -e

OUT_DIR=
tidb_config=
retry_times=3

while [[ ${1} ]]; do
    case "${1}" in
        --workdir)
            OUT_DIR=${2}
            shift
            ;;
        --tidb-config)
            tidb_config=${2}
            shift
            ;;
        --retry)
            retry_times=${2}
            shift
            ;;
        *)
            echo "Unknown parameter: ${1}" >&2
            exit 1
    esac

    if ! shift; then
        echo 'Missing parameter argument.' >&2
        exit 1
    fi
done

CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source $CUR/../_utils/test_prepare

set +e
i=1
while [ $i -le $retry_times ]
do
    echo "The ${i} times to try to start tidb cluster..."

    if [[ "$tidb_config" != "" ]]; then
        start_tidb_cluster_impl --workdir ${OUT_DIR} --tidb-config ${tidb_config}
    else
        start_tidb_cluster_impl --workdir ${OUT_DIR}
    fi

    if [ $? -eq 0 ]; then
        break
    fi
    let i++
    echo "start tidb cluster failed"
done