#!/bin/bash

killall -w -s 9 tikv-server || true
killall -w -s 9 pd-server || true
killall -w -s 9 tidb-server || true
killall -w -s 9 cdc || true
killall -w -s 9 cdc.test || true
killall -w -s 9 tiflash || true

kill -9 $(lsof -i tcp:4000 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:4001 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:10080 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:10081 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:3306 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:20080 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:2379 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:2380 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:2479 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:2480 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:20160 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:20181 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:20161 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:20182 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:20162 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:20183 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:21160 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:21180 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:9500 -t) &>/dev/null || true
kill -9 $(lsof -i tcp:17000 -t) &>/dev/null || true
