version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/dm/ui"
    schedule:
      interval: "weekly"
      day: "monday"
    # Specify labels for npm pull requests.
    labels:
      - "dependencies"
      - "javascript"
      - "release-note-none"
