// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/srvdiscovery/interface.go

// Package mock_srvdiscovery is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	srvdiscovery "github.com/hanfei1991/microcosm/pkg/srvdiscovery"
)

// MockDiscovery is a mock of Discovery interface.
type MockDiscovery struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveryMockRecorder
}

// MockDiscoveryMockRecorder is the mock recorder for MockDiscovery.
type MockDiscoveryMockRecorder struct {
	mock *MockDiscovery
}

// NewMockDiscovery creates a new mock instance.
func NewMockDiscovery(ctrl *gomock.Controller) *MockDiscovery {
	mock := &MockDiscovery{ctrl: ctrl}
	mock.recorder = &MockDiscoveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscovery) EXPECT() *MockDiscoveryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDiscovery) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDiscoveryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDiscovery)(nil).Close))
}

// CopySnapshot mocks base method.
func (m *MockDiscovery) CopySnapshot(snapshot map[srvdiscovery.UUID]srvdiscovery.ServiceResource, revision srvdiscovery.Revision) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CopySnapshot", snapshot, revision)
}

// CopySnapshot indicates an expected call of CopySnapshot.
func (mr *MockDiscoveryMockRecorder) CopySnapshot(snapshot, revision interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopySnapshot", reflect.TypeOf((*MockDiscovery)(nil).CopySnapshot), snapshot, revision)
}

// Snapshot mocks base method.
func (m *MockDiscovery) Snapshot(ctx context.Context) (map[srvdiscovery.UUID]srvdiscovery.ServiceResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx)
	ret0, _ := ret[0].(map[srvdiscovery.UUID]srvdiscovery.ServiceResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockDiscoveryMockRecorder) Snapshot(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockDiscovery)(nil).Snapshot), ctx)
}

// SnapshotClone mocks base method.
func (m *MockDiscovery) SnapshotClone() (map[srvdiscovery.UUID]srvdiscovery.ServiceResource, srvdiscovery.Revision) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotClone")
	ret0, _ := ret[0].(map[srvdiscovery.UUID]srvdiscovery.ServiceResource)
	ret1, _ := ret[1].(srvdiscovery.Revision)
	return ret0, ret1
}

// SnapshotClone indicates an expected call of SnapshotClone.
func (mr *MockDiscoveryMockRecorder) SnapshotClone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotClone", reflect.TypeOf((*MockDiscovery)(nil).SnapshotClone))
}

// Watch mocks base method.
func (m *MockDiscovery) Watch(ctx context.Context) <-chan srvdiscovery.WatchResp {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx)
	ret0, _ := ret[0].(<-chan srvdiscovery.WatchResp)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockDiscoveryMockRecorder) Watch(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockDiscovery)(nil).Watch), ctx)
}
