linters:
  enable:
    - unconvert
    - unparam
    - revive

linters-settings:
  revive:
    ignore-generated-header: false
    severity: error
    confidence: 0.8
    error-code: -1
    warning-code: -1
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: modifies-parameter
      - name: unreachable-code
