FROM golang:1.18-alpine as builder

RUN apk add --no-cache gcompat

COPY ./bin/master ./bin/
COPY ./bin/executor ./bin/

RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64 && \
    chmod +x /usr/local/bin/dumb-init

ENTRYPOINT ["/usr/local/bin/dumb-init"]
