# Default values for tiflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# clusterName: demo

image:
  repository: dataflow
  pullPolicy: IfNotPresent
  # Overwrite this image tags according to the actual deployment requirements
  tag: chaos

master:
  replicas: 3
  dataStorage: 2Gi
  logStorage: 1Gi
  config: |
    [framework-meta]
    user = "root"
    password = ""
    schema = "test_framework"

    [business-meta]
    user = "root"
    password = ""
    schema = "test_business"

executor:
  replicas: 4
  logStorage: 1Gi
  config: |
    keepalive-ttl = "20s"
    keepalive-interval = "500ms"
    session-ttl = 20

metastore:
  frameworkStorage: 5Gi
  businessStorage: 5Gi

cases:
  enabled: false
  repository: dataflow
  tag: chaos
