version: '2.3'

services:
  etcd-standalone:
    image: quay.io/coreos/etcd
    container_name: etcd-standalone
    volumes:
      - ./config/etcd.yml:/etcd.yml
    command:
      - "etcd"
      - "--config-file=/etcd.yml"
    ports:
      - "12479:2379"
      - "12480:2380"
  mysql-standalone:
    image: mysql:5.7
    container_name: mysql_standalone
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - '/tmp/dataflow/mysql:/var/lib/mysql'
      - './config/mysql_meta.cnf:/etc/my.cnf'
    ports:
      - "3336:3306"
    healthcheck:
      test: "mysqladmin ping -h127.0.0.1 -P3306 -uroot -p123456"
      interval: 10s
      timeout: 600s
      retries: 60
