linters:
  enable:
    - unconvert
    - unparam
    - revive
    - depguard
    - misspell
    - ineffassign
    - typecheck
    - varcheck
    - unused
    - structcheck
    - deadcode
    - gosimple
    - goimports
    - errcheck
    - staticcheck
    - stylecheck
    - gosec
    - asciicheck
    - exportloopref
    - makezero

linters-settings:
  revive:
    ignore-generated-header: false
    severity: error
    confidence: 0.8
    error-code: -1
    warning-code: -1
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: var-naming
      - name: package-comments
      - name: range
#      - name: receiver-naming TODO disable it because it can't handle generics
      - name: indent-error-flow
      - name: superfluous-else
      - name: modifies-parameter
      - name: unreachable-code

  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - log
      - github.com/juju/errors
    packages-with-error-message:
      # specify an error message to output when a blacklisted package is used
      - log: "logging is allowed only by pingcap/log"
      - github.com/juju/errors: "error handling is allowed only by pingcap/errors"
  staticcheck:
    checks: ["S1002","S1004","S1007","S1009","S1010","S1012","S1019","S1020","S1021","S1024","S1030","SA2*","SA3*","SA4009","SA5*","SA6000","SA6001","SA6005", "-SA2002"]
  stylecheck:
    checks: ["-ST1003"]
  gosec:
    excludes:
      - G404
      - G601
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - makezero
  include:
    - EXC0012 # exported (.+) should have comment( \(or a comment on this block\))? or be unexported)
    - EXC0014 # comment on exported (.+) should be of the form "(.+)..."

run:
  go: 1.18
