{
 "title": "DM-Monitor-Standard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "label": "K8s-cluster",
    "query": {
     "query": "label_values(go_goroutines, k8s_cluster)"
    }
   },
   {
    "name": "tidb_cluster",
    "label": "tidb_cluster",
    "query": {
     "query": "label_values(go_goroutines{k8s_cluster=\"$k8s_cluster\"}, tidb_cluster)"
    }
   },
   {
    "name": "job_id",
    "label": "JobID",
    "query": {
     "query": "label_values(dm_worker_task_state, job_id)"
    }
   },
   {
    "name": "task",
    "label": "Task",
    "query": {
     "query": "label_values(dm_worker_task_state, task)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(dm_worker_task_state, source_id)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(dm_worker_task_state{task=~\"$task\"}, instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(dm_worker_task_state, worker)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Task Count",
   "type": "stat",
   "description": "The current state of subtasks in instances.\n\n0: Invalid\n\n1: New\n\n2: Running\n\n3: Paused\n\n4: Stopped\n\n5: Finished",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(dm_worker_task_state{job_id=~\"$job_id\"} == 2)"
    }
   ]
  },
  {
   "title": "Task Not Running",
   "type": "table",
   "description": "The current state of subtasks in instances.\n\n0: Invalid\n\n1: New\n\n2: Running\n\n3: Paused\n\n4: Stopped\n\n5: Finished",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "dm_worker_task_state{job_id=~\"$job_id\"} != 2 "
    }
   ]
  },
  {
   "title": "Remaining time to sync",
   "type": "graph",
   "description": "The predicted remaining time it takes Syncer to be completely synchronized with the master\n\nThis indicator is rough and crude and may vary greatly due to environmental factors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "dm_syncer_remaining_time{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}",
     "legendFormat": "{{task}} - {{source_id}}"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "graph",
   "description": "The latency time it takes to replicate the binlog from master to Syncer (in seconds)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_replication_lag_bucket{source_id=~\"$source\",task=~\"$task\"}[$interval])) by (le,task,source_id))",
     "legendFormat": "{{task}} - {{source_id}} - 90"
    },
    {
     "expr": "histogram_quantile(0.95,\nsum(rate(dm_syncer_replication_lag_bucket{source_id=~\"$source\",task=~\"$task\"}[$interval])) by (le,task,source_id))",
     "legendFormat": "{{task}} - {{source_id}} - 95"
    },
    {
     "expr": "histogram_quantile(0.99,\nsum(rate(dm_syncer_replication_lag_bucket{source_id=~\"$source\",task=~\"$task\"}[$interval])) by (le,task,source_id))",
     "legendFormat": "{{task}} - {{source_id}} - 99"
    }
   ]
  },
  {
   "title": "Replication TPS",
   "type": "graph",
   "description": "number of dm transaction executed per second (one minute average value)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (task,source_id) (rate(dm_syncer_finished_transaction_total{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[1m]))",
     "legendFormat": "{{task}} - {{source_id}}"
    }
   ]
  },
  {
   "title": "Replication QPS",
   "type": "graph",
   "description": "number of sql executed per second(one minute average value )",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (task,source_id) (rate(dm_syncer_finished_jobs_total{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[$interval]))",
     "legendFormat": "{{task}} - {{source_id}}"
    }
   ]
  },
  {
   "title": "transaction/ddl query execution latency",
   "type": "graph",
   "description": "The time it takes binlog replication unit to execute the transaction to the downstream (in seconds)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_txn_duration_time_bucket{worker=~\"$worker\",task=~\"$task\"}[$interval])) by (le,worker,task))",
     "legendFormat": "{{task}} - txn-90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_txn_duration_time_bucket{worker=~\"$worker\",task=~\"$task\"}[$interval])) by (le,worker,task))",
     "legendFormat": "{{task}} - txn-95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_txn_duration_time_bucket{worker=~\"$worker\",task=~\"$task\"}[$interval])) by (le,worker,task))",
     "legendFormat": "{{task}} - txn-99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_query_duration_time_bucket{worker=~\"$worker\",task=~\"$task\"}[$interval])) by (le,worker,task))",
     "legendFormat": "{{task}} - ddl-90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_query_duration_time_bucket{worker=~\"$worker\",task=~\"$task\"}[$interval])) by (le,worker,task))",
     "legendFormat": "{{task}}- ddl-95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_query_duration_time_bucket{worker=~\"$worker\",task=~\"$task\"}[$interval])) by (le,worker,task))",
     "legendFormat": "{{task}} - ddl-99"
    }
   ]
  },
  { "title": "dump and load ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "dump progress",
   "type": "graph",
   "description": "The data import process percentage of dump unit. The value is an estimated value and may exceed less than 100%.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dumpling_dump_finished_rows{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"} / dumpling_dump_estimate_total_rows{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}",
     "legendFormat": "{{task}} - {{source_id}}"
    }
   ]
  },
  {
   "title": "load progress",
   "type": "graph",
   "description": "The data import process percentage of load unit. The value range is 0% ~ 100%",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "lightning_chunks{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\",state=\"finished\"} / ignoring(state) lightning_chunks{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\",state=\"estimated\"}",
     "legendFormat": "{{task}} - {{source_id}}"
    }
   ]
  },
  {
   "title": "checksum progress",
   "type": "graph",
   "description": "The checksum process percentage of load unit. The value range is 0% ~ 100%",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "lightning_tables{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\",state=\"completed\"} / ignoring(state) lightning_tables{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\",state=\"pending\"}",
     "legendFormat": "{{task}} - {{source_id}}"
    }
   ]
  },
  {
   "title": "Total bytes for load unit",
   "type": "graph",
   "description": "The statistic of bytes in different status of data files processed by load unit",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "lightning_row_read_bytes_sum{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}",
     "legendFormat": "parser read size - {{task}} - {{source_id}}"
    },
    {
     "expr": "lightning_block_deliver_bytes_sum{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}",
     "legendFormat": "{{kind}} deliver size - {{task}} - {{source_id}}"
    }
   ]
  },
  {
   "title": "Chunk process duration",
   "type": "graph",
   "description": "The duration that load unit process a chunk",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(lightning_chunks{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\",state=\"finished\"}[1m])",
     "legendFormat": "{{task}} - {{source_id}}"
    }
   ]
  }
 ]
}