{
 "title": "DM-Monitor-Professional",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "label": "K8s-cluster",
    "query": {
     "query": "label_values(go_goroutines, k8s_cluster)"
    }
   },
   {
    "name": "tidb_cluster",
    "label": "tidb_cluster",
    "query": {
     "query": "label_values(go_goroutines{k8s_cluster=\"$k8s_cluster\"}, tidb_cluster)"
    }
   },
   {
    "name": "job_id",
    "label": "JobID",
    "query": {
     "query": "label_values(dm_worker_task_state, job_id)"
    }
   },
   {
    "name": "task",
    "label": "Task",
    "query": {
     "query": "label_values(dm_worker_task_state, task)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(dm_worker_task_state, source_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dm_worker_task_state{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\"}, instance)"
    }
   },
   {
    "name": "queueNo",
    "label": "Queue",
    "query": {
     "query": "label_values(dm_syncer_finished_jobs_total, queueNo)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(dm_syncer_finished_jobs_total,type)"
    }
   },
   {
    "name": "stage",
    "label": "Stage",
    "query": {
     "query": "label_values(dm_syncer_binlog_transform_cost_count,stage)"
    }
   },
   {
    "name": "target_schema",
    "label": "Target Schema",
    "query": {
     "query": "label_values(dm_syncer_finished_jobs_total, target_schema)"
    }
   },
   {
    "name": "target_table",
    "label": "Target_table",
    "query": {
     "query": "label_values(dm_syncer_finished_jobs_total, target_table)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(dm_syncer_finished_jobs_total,worker)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Task State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dm_worker_task_state{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}",
     "legendFormat": "{{task}}-{{source_id}}-{{worker}}"
    }
   ]
  },
  {
   "title": "dump and load ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "dump progress",
     "type": "graph",
     "description": "The data import process percentage of dump unit. The value is an estimated value and may exceed less than 100%.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "dumpling_dump_finished_rows{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"} / dumpling_dump_estimate_total_rows{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "load progress",
     "type": "graph",
     "description": "The data import process percentage of load unit. The value range is 0% ~ 100%",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "lightning_chunks{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\",state=\"finished\"} / ignoring(state) lightning_chunks{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\",state=\"estimated\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "checksum progress",
     "type": "graph",
     "description": "The checksum process percentage of load unit. The value range is 0% ~ 100%",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "lightning_tables{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\",state=\"completed\"} / ignoring(state) lightning_tables{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\",state=\"pending\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "dump process exits with error",
     "type": "graph",
     "description": "Dumper encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(dm_dumpling_exit_with_error_count{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}[30m])",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "load process exits with error",
     "type": "graph",
     "description": "load unit encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(dm_loader_exit_with_error_count{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}[30m])",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "Idle workers",
     "type": "graph",
     "description": "idle load unit workers",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "lightning_idle_workers{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "{{name}} - {{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "Chunk process duration",
     "type": "graph",
     "description": "The duration that load unit process a chunk (in seconds)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "1/rate(lightning_chunks{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\",state=\"finished\"}[1m])",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "External resources",
     "type": "graph",
     "description": "The number of external resources used by load unit",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "lightning_kv_encoder{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\", type=\"open\"} - ignoring(type) lightning_kv_encoder{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\", type=\"closed\"}",
       "legendFormat": "KV Encoder"
      },
      {
       "expr": "lightning_importer_engine{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\", type=\"open\"} - ignoring(type) lightning_importer_engine{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\", type=\"closed\"}",
       "legendFormat": "Importer Engines (via Lightning)"
      }
     ]
    },
    {
     "title": "Total bytes for load unit",
     "type": "graph",
     "description": "The statistic of bytes in different status of data files processed by load unit",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "lightning_row_read_bytes_sum{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "parser read size - {{task}} - {{source_id}}"
      },
      {
       "expr": "lightning_block_deliver_bytes_sum{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "{{kind}} deliver size - {{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "SQL process rate",
     "type": "graph",
     "description": "The speed of load unit processing source files internally",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(lightning_block_deliver_bytes_sum{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}[30s])",
       "legendFormat": "{{kind}} deliver rate {{task}} - {{source_id}}"
      },
      {
       "expr": "sum(rate(lightning_block_deliver_bytes_sum{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}[30s]))",
       "legendFormat": "total deliver rate {{task}} - {{source_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "binlog replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication QPS",
     "type": "graph",
     "description": "number of sql executed per second(one minute average value, dm_syncer_finished_jobs_total )",
     "gridPos": { "h": 12, "w": 15, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dm_syncer_finished_jobs_total{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\",target_schema=~\"$target_schema\",type=~\"$type\"}[$interval]))by (task,source_id,target_schema,type)",
       "legendFormat": "{{task}} - {{target_schema}} -  {{type}} "
      }
     ]
    },
    {
     "title": "Remaining time to sync",
     "type": "graph",
     "description": "The predicted remaining time it takes Syncer to be completely synchronized with the master (in seconds)",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_remaining_time{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "Replication lag",
     "type": "graph",
     "description": "The latency time it takes to replicate the binlog from master to Syncer (in seconds)",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_replication_lag_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,source_id,task))",
       "legendFormat": "{{task}} - {{source_id}} - 90"
      },
      {
       "expr": "dm_syncer_replication_lag_gauge{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}",
       "legendFormat": "{{task}} - {{source_id}} - gauge"
      }
     ]
    },
    {
     "title": "Replication QPS (Sum by task)",
     "type": "graph",
     "description": "number of sql executed per second(one minute average value, dm_syncer_finished_jobs_total )\n\nThe maximum TPS estimated according to the recent SQL time-consuming, may vary greatly with different SQL",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dm_syncer_finished_jobs_total{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\"}[$interval])) by (task)",
       "legendFormat": "{{task}} "
      },
      {
       "expr": "sum(dm_syncer_ideal_qps{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\"}) by (task)",
       "legendFormat": "{{task}} - ideal"
      }
     ]
    },
    {
     "title": "process exits with error",
     "type": "graph",
     "description": "The binlog replication unit process encounters an error within the DM-worker and exits",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(dm_syncer_exit_with_error_count{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[30m])",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "DM SQL jobs ",
     "type": "graph",
     "description": "The number of add/finished jobs per unit of time",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dm_syncer_finished_jobs_total{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\",target_schema=~\"$target_schema\",type=~\"$type\"}[$interval])) by (task,source_id,target_schema,type)",
       "legendFormat": "finished-{{task}} - {{target_schema}} - {{type}} "
      },
      {
       "expr": "sum(-rate(dm_syncer_added_jobs_total{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\",target_schema=~\"$target_schema\",type=~\"$type\"}[$interval])) by (task,source_id,target_schema,type)",
       "legendFormat": "add-{{task}} - {{target_schema}} - {{type}}"
      }
     ]
    },
    {
     "title": "DML conflict detect duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to detect conflicts between DMLs (in seconds)",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_conflict_detect_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\"}[$interval])) by (le,task))",
       "legendFormat": "{{task}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_conflict_detect_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\"}[$interval])) by (le,task))",
       "legendFormat": "{{task}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_conflict_detect_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\"}[$interval])) by (le,task))",
       "legendFormat": "{{task}} - 99"
      }
     ]
    },
    {
     "title": "binlog event QPS",
     "type": "graph",
     "description": "The number of binlog events received per unit of time (this number does not include the events that need to be skipped)",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,task,stage) (rate(dm_syncer_binlog_transform_cost_count{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\", source_id=~\"$source\",stage=~\"$stage\"}[$interval]))",
       "legendFormat": "{{task}} - {{instance}} - {{stage}}"
      }
     ]
    },
    {
     "title": "add job duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to add a job to the queue (in seconds)",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum (rate(dm_syncer_add_job_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\",queueNo=~\"$queueNo\",type=~\"$type\"}[$interval])) by (task,le))",
       "legendFormat": "{{task}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_add_job_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\",queueNo=~\"$queueNo\",type=~\"$type\"}[$interval])) by (task,le))",
       "legendFormat": "{{task}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_add_job_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\",queueNo=~\"$queueNo\",type=~\"$type\"}[$interval])) by (task,le))",
       "legendFormat": "{{task}}  - 99"
      }
     ]
    },
    {
     "title": "transaction/ddl query execution latency",
     "type": "graph",
     "description": "The time it takes binlog replication unit to execute the transaction to the downstream (in seconds)",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_txn_duration_time_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - txn-90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_txn_duration_time_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - txn-95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_txn_duration_time_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - txn-99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_query_duration_time_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - ddl-90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_query_duration_time_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - ddl-95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_query_duration_time_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - ddl-99"
      }
     ]
    },
    {
     "title": "statement execution latency - 90",
     "type": "graph",
     "description": "The time it takes binlog replication unit to execute every statement to the downstream (in seconds)",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", type=\"begin\", instance=~\"$instance\"}[$interval])) by (le,task,instance))",
       "legendFormat": "{{task}} - {{instance}} - begin"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", type=\"stmt\", instance=~\"$instance\"}[$interval])) by (le,task,instance))",
       "legendFormat": "{{task}} - {{instance}} - stmt"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", type=\"commit\", instance=~\"$instance\"}[$interval])) by (le,task,instance))",
       "legendFormat": "{{task}} - {{instance}} - commit"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", type=\"rollback\", instance=~\"$instance\"}[1m])) by (le,task,instance))",
       "legendFormat": "{{task}} - {{instance}} - rollback"
      }
     ]
    },
    {
     "title": "skipped binlog event QPS",
     "type": "graph",
     "description": "The number of binlog events received per unit of time that needs to be skipped",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dm_syncer_skip_binlog_duration_count{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\", type=\"rows\"}[$interval])",
       "legendFormat": "{{task}} - {{source_id}} - rows"
      },
      {
       "expr": "rate(dm_syncer_skip_binlog_duration_count{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\", type=\"query\"}[$interval])",
       "legendFormat": "{{task}} - {{source_id}} - query"
      }
     ]
    },
    {
     "title": "DML queue remain length",
     "type": "graph",
     "description": "The remain length of DML job queues",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dm_syncer_queue_size{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\"}) by (task)",
       "legendFormat": "{{task}}"
      }
     ]
    },
    {
     "title": "binlog event size",
     "type": "graph",
     "description": "The size of a single binlog event that the binlog replication unit reads from relay log or upstream master",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_event_size_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",worker=~\"$worker\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,worker,task))",
       "legendFormat": "{{task}} - {{worker}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_binlog_event_size_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",worker=~\"$worker\",task=~\"$task\", source_id=~\"$source\"}[1m])) by (le,worker,task))",
       "legendFormat": "{{task}} - {{worker}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_binlog_event_size_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",worker=~\"$worker\",task=~\"$task\", source_id=~\"$source\"}[1m])) by (le,worker,task))",
       "legendFormat": "{{task}} - {{worker}} - 99"
      }
     ]
    },
    {
     "title": "binlog file gap between master and syncer",
     "type": "graph",
     "description": "The number of binlog files in binlog replication unit that are behind the master",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "clamp_min(dm_syncer_binlog_file{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",source_id=~\"$source\", task=~\"$task\", node=\"master\"} - ON(task,source_id) dm_syncer_binlog_file{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",source_id=~\"$source\", task=~\"$task\", node=\"syncer\"}, 0)",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "binlog event row number",
     "type": "graph",
     "description": "The number of rows of each binlog event that enters the DM",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_event_row_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\",source_id=~\"$source\"}[$interval])) by (le,task,source))",
       "legendFormat": "{{task}}-{{source}}"
      }
     ]
    },
    {
     "title": "read binlog event duration",
     "type": "graph",
     "description": "The duration that the binlog replication unit reads binlog event from the relay log or upstream MySQL (in seconds)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_read_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_read_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_read_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 99"
      }
     ]
    },
    {
     "title": "binlog event cost duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to parse and transform the binlog into SQL statements (in seconds)",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 69 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_transform_cost_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",worker=~\"$worker\",task=~\"$task\", source_id=~\"$source\"}[1m])) by (le,worker,task,stage))",
       "legendFormat": "90-[[worker]]-[[task]]-{{stage}}"
      }
     ]
    },
    {
     "title": "dispatch binlog event duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to dispatch a binlog event (in seconds)",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 69 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_dispatch_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_dispatch_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_dispatch_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 99"
      }
     ]
    },
    {
     "title": "unsynced tables",
     "type": "graph",
     "description": "The number of unsynced tables in the subtask",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_unsynced_table_number{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",source_id=~\"$source\", task=~\"$task\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "binlog file gap between relay and syncer",
     "type": "graph",
     "description": "The number of binlog files in binlog replication unit that are behind relay",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\", node=\"relay\"} - ON(instance) group_right dm_syncer_binlog_file{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\", task=~\"$task\", node=\"syncer\"}",
       "legendFormat": "{{instance}} - {{task}}"
      }
     ]
    },
    {
     "title": "Flushed Checkpoint Time Interval",
     "type": "graph",
     "description": "The time interval of DM written to disk",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_flush_checkpoints_time_interval_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\"}[$interval])) by (le,task,worker))",
       "legendFormat": "{{task}}-{{worker}}"
      }
     ]
    },
    {
     "title": "shard lock resolving",
     "type": "graph",
     "description": "Is waiting shard DDL lock to be resolved, >0 means waiting",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_shard_lock_resolving{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",source_id=~\"$source\", task=~\"$task\"}",
       "legendFormat": "{{task}} - {{source}}"
      }
     ]
    },
    {
     "title": "skip event duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to skip a binlog event (in seconds)",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 85 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_skip_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_skip_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_skip_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 99"
      }
     ]
    },
    {
     "title": "replication transaction batch",
     "type": "graph",
     "description": "Display the number of sql contained in the dm copy incremental data to the downstream transaction from each latitude",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_replication_transaction_batch_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task,queueNo,type))",
       "legendFormat": "{{task}} - {{queueNo}} - {{type}}"
      }
     ]
    },
    {
     "title": " transform binlog event duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_transform_cost_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{source_id}} - {{instance}} -  90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_binlog_transform_cost_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{source_id}} - {{instance}} -  95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_binlog_transform_cost_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{source_id}} - {{instance}} -  99"
      }
     ]
    }
   ]
  },
  {
   "title": "relay log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "storage capacity",
     "type": "graph",
     "description": "The storage capacity of the disk occupied by the relay log",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dm_relay_space{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\", type=\"capacity\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "storage remain",
     "type": "graph",
     "description": "The remaining storage capacity of the disk occupied by the relay log",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dm_relay_space{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\", type=\"available\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process exits with error",
     "type": "graph",
     "description": "The relay log encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_exit_with_error_count{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}",
       "legendFormat": " {{instance}}"
      }
     ]
    },
    {
     "title": "relay log data corruption",
     "type": "graph",
     "description": "The number of corrupted relay log files",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_data_corruption{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fail to read binlog from master",
     "type": "graph",
     "description": "The number of errors encountered when the relay log reads the binlog from the upstream MySQL",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_read_error_count{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fail to write relay log",
     "type": "graph",
     "description": "The number of errors encountered when the relay log writes the binlog to disks",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_write_error_count{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "binlog file index",
     "type": "graph",
     "description": "The largest index number of relay log files. E.g. \"value = 1\" indicates \"mysql-bin.000001\"",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\", node=\"master\"}",
       "legendFormat": "master"
      },
      {
       "expr": "dm_relay_binlog_file{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\", node=\"relay\"}",
       "legendFormat": "relay"
      }
     ]
    },
    {
     "title": "binlog file gap between master and relay",
     "type": "graph",
     "description": "The number of binlog files in the relay log that are behind the upstream master",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\", node=\"master\"} - ON(instance) dm_relay_binlog_file{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\", node=\"relay\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "binlog pos",
     "type": "graph",
     "description": "The write offset of the latest relay log file",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_pos{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\", node=\"master\"}",
       "legendFormat": "master - {{instance}}"
      },
      {
       "expr": "dm_relay_binlog_pos{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\", node=\"relay\"}",
       "legendFormat": "relay - {{instance}}"
      }
     ]
    },
    {
     "title": "read binlog event duration",
     "type": "graph",
     "description": "The duration that the relay log reads binlog event from the upstream MySQL (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_relay_read_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_relay_read_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_relay_read_binlog_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "write relay log duration",
     "type": "graph",
     "description": "The duration that the relay log writes binlog event into the disks each time (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_relay_write_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_relay_write_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_relay_write_duration_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "binlog event size",
     "type": "graph",
     "description": "The size of a single binlog event that the relay log writes into the disks",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_relay_write_size_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_relay_write_size_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_relay_write_size_bucket{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\", job_id=~\"$job_id\",instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    }
   ]
  },
  {
   "title": "HA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "number of dm-masters start leader components per minute",
     "type": "graph",
     "description": "number of dm-masters try to start leader components per minute",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_master_start_leader_counter{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "number of workers in different state",
     "type": "graph",
     "description": "number of worker in different states, -1 - unrecognized, 0 - offline, 1 - free, 2 - bound",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_values(\"state\", dm_master_worker_state{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\"})"
      }
     ]
    },
    {
     "title": "workers' state",
     "type": "graph",
     "description": "state of worker, -1 - unrecognized, 0 - offline, 1 - free, 2 - bound",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (dm_master_worker_state{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\"})"
      }
     ]
    },
    {
     "title": "number of worker event error",
     "type": "graph",
     "description": "number of worker event error",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (dm_master_worker_event_error{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\"})"
      }
     ]
    },
    {
     "title": "shard ddl error per minute",
     "type": "graph",
     "description": "number of shard DDL lock/operation error in one minute",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (task, type) (increase(dm_master_shard_ddl_error{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\"}[1m]))"
      }
     ]
    },
    {
     "title": "number of pending shard ddl",
     "type": "graph",
     "description": "number of pending shard DDL in different states, Un-synced (waiting all upstream), Synced (all upstream finished, waiting all downstream)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (task, type) (dm_master_ddl_state_number{k8s_cluster=~\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "operate error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "before any operate error",
     "type": "graph",
     "description": "The number of error happens before operate",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{k8s_cluster=~\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster\", type=\"BeforeAnyOp\"}"
      }
     ]
    },
    {
     "title": "source bound error",
     "type": "graph",
     "description": "The number of error happens in operate source bound",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{k8s_cluster=~\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster\", type=\"SourceBound\"}"
      }
     ]
    },
    {
     "title": "start error",
     "type": "graph",
     "description": "The number of error happens in operate start",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{k8s_cluster=~\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster\", type=\"Start\"}"
      }
     ]
    },
    {
     "title": "pause error",
     "type": "graph",
     "description": "The number of error happens in operate pause",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{k8s_cluster=~\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster\", type=\"Pause\"}"
      }
     ]
    },
    {
     "title": "resume error",
     "type": "graph",
     "description": "The number of error happens in operate resume",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{k8s_cluster=~\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster\", type=\"Resume\"}"
      }
     ]
    },
    {
     "title": "auto-resume error",
     "type": "graph",
     "description": "The number of error happens in operate auto-resume",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{k8s_cluster=~\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster\", type=\"AutoResume\"}"
      }
     ]
    },
    {
     "title": "update error",
     "type": "graph",
     "description": "The number of error happens in operate update",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{k8s_cluster=~\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster\", type=\"Update\"}"
      }
     ]
    },
    {
     "title": "stop error",
     "type": "graph",
     "description": "The number of error happens in operate stop",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{k8s_cluster=~\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster\", type=\"Stop\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Validator Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validator Error Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_validator_validator_error_count{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\"}"
      }
     ]
    },
    {
     "title": "Validator Binlog Latency (in byte)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_validator_validator_logpos_latency{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\"}"
      }
     ]
    },
    {
     "title": "Validator Binlog Position (in file)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_validator_validator_binlog_file{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\"}"
      }
     ]
    },
    {
     "title": "Validator Binlog Latency (in file)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_validator_validator_logfile_latency{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\"}"
      }
     ]
    },
    {
     "title": "Validator Binlog Position (in byte)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_validator_validator_binlog_pos{k8s_cluster=~\"$k8s_cluster\",tidb_cluster=~\"$tidb_cluster\"}"
      }
     ]
    }
   ]
  }
 ]
}