{
 "title": "Cluster-Tiflow",
 "description": "dashboard for tiflow cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "label": "K8s_cluster",
    "query": {
     "query": "label_values(go_goroutines, k8s_cluster)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_goroutines, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "CPU usage of Tiflow Engine",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "description": "Memory usage of Tiflow Engine",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}",
     "legendFormat": "process-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}",
     "legendFormat": "heap-{{instance}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Num of Job State",
   "type": "timeseries",
   "description": "num of different job state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max(dataflow_tiflow_server_master_job_num{k8s_cluster=\"$k8s_cluster\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Num of Executor State",
   "type": "timeseries",
   "description": "num of different executor state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "max(dataflow_tiflow_server_master_executor_num{k8s_cluster=\"$k8s_cluster\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Tiflow process rss memory usage. Tiflow heap memory size in use.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}",
     "legendFormat": "alloc-from-os-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"} - go_memstats_heap_released_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"} + go_memstats_heap_inuse_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"} - go_memstats_heap_alloc_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}",
     "legendFormat": "reserved-by-go-{{instance}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"} + go_memstats_mspan_sys_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"} + go_memstats_mcache_sys_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"} + go_memstats_buck_hash_sys_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"} + go_memstats_gc_sys_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"} + go_memstats_other_sys_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}",
     "legendFormat": "used-by-go-{{instance}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}",
     "legendFormat": "gc-threshold-{{instance}}"
    },
    {
     "expr": "(clamp_max(idelta(go_memstats_last_gc_time_seconds{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}[1m]), 1) * go_memstats_next_gc_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}) > 0",
     "legendFormat": "gc-{{instance}}"
    }
   ]
  },
  {
   "title": "Estimated Live Objects",
   "type": "timeseries",
   "description": "Count of live objects.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}",
     "legendFormat": "objects-{{instance}}"
    }
   ]
  },
  {
   "title": "GC STW Duration (last 256 GC cycles)",
   "type": "timeseries",
   "description": "Tiflow Engine process Go garbage collection STW pause duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0\", k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}",
     "legendFormat": "min-{{instance}}"
    },
    {
     "expr": "go_gc_duration_seconds{quantile!~\"0|1\", k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{quantile}}-{{instance}}"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"1\", k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}",
     "legendFormat": "max-{{instance}}"
    }
   ]
  },
  {
   "title": "Allocator Throughput",
   "type": "timeseries",
   "description": "The throughput of Go's memory allocator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(go_memstats_alloc_bytes_total{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}[30s])",
     "legendFormat": "alloc-{{instance}}"
    },
    {
     "expr": "irate((go_memstats_alloc_bytes_total{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"} - go_memstats_heap_alloc_bytes{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"})[30s:])",
     "legendFormat": "sweep-{{instance}}"
    },
    {
     "expr": "irate(go_memstats_mallocs_total{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}[30s])",
     "legendFormat": "alloc-ops-{{instance}}"
    },
    {
     "expr": "irate(go_memstats_frees_total{k8s_cluster=\"$k8s_cluster\", instance=~\"$instance\"}[30s])",
     "legendFormat": "sweep-ops-{{instance}}"
    }
   ]
  }
 ]
}