etcd-endpoints = ["etcd-standalone:2379"]

[framework-meta]
endpoints = ["mysql-standalone:3306"]
schema = "test_framework"
user = "root"
password = ""

[business-meta]
endpoints = ["mysql-standalone:3306"]
schema = "test_business"
user = "root"
password = ""

[log] 
level = "debug"
