apiVersion: chaos-mesh.org/v1alpha1
kind: IoChaos
metadata:
  name: io-delay-cdc
  labels:
    app: io-delay-cdc
spec:
  action: latency
  mode: one
  selector:
    pods:
      playground:
        - cdc-0
        - upstream-tikv-0
        - upstream-pd-0
        - downstream-tikv-0
  volumePath: /data
  path: "/data/**/*"
  delay: "100ms"
  percent: 50
  duration: "60s"
  scheduler:
    cron: "@every 2m"
