apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss-cdc
  labels:
    app: network-loss-cdc
spec:
  action: loss
  mode: one
  selector:
    pods:
      playground:
        - cdc-0
        - upstream-tikv-0
        - upstream-pd-0
        - downstream-tidb-0
  loss:
    loss: "25"
    correlation: "25"
  duration: "30s"
  scheduler:
    cron: "2-59/3 * * * *" # At every 3th minute from 2 through 59, (2, 5, 8, ...)


# A Network Delay action causes delays in message sending
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-cdc
  labels:
    app: network-delay-cdc
spec:
  action: delay
  mode: one
  selector:
    pods:
      playground:
        - cdc-0
        - upstream-tikv-0
        - upstream-pd-0
        - downstream-tidb-0
  delay:
    latency: "90ms"
    correlation: "25"
    jitter: "90ms"
  duration: "30s"
  scheduler:
    cron: "3-59/3 * * * *" # At every 5th minute from 3 through 59, (3, 6, 9, ...)

---
# A Network Duplicate action causes packet duplication
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-cdc
  labels:
    app: network-cdc
spec:
  action: duplicate
  mode: one
  selector:
    pods:
      playground:
        - cdc-0
        - upstream-tikv-0
        - upstream-pd-0
        - downstream-tidb-0
  duplicate:
    duplicate: "40"
    correlation: "25"
  duration: "30s"
  scheduler:
    cron: "4-59/3 * * * *" # At every 5th minute from 4 through 59, (4, 7, 10, ...)

---
# A Network Corrupt action causes packet corruption
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-corrupt-cdc
  labels:
    app: network-corrupt-cdc
spec:
  action: corrupt
  mode: one
  selector:
    pods:
      playground:
        - cdc-0
        - upstream-tikv-0
        - upstream-pd-0
        - downstream-tidb-0
  corrupt:
    corrupt: "40"
    correlation: "25"
  duration: "30s"
  scheduler:
    cron: "5-59/3 * * * *" # At every 5th minute from 5 through 59, (5, 8, 11, ...)
