apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: io-delay-dm
  labels:
    app: io-delay-dm
spec:
  schedule: '@every 2m'
  type: IOChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  ioChaos:
    action: latency
    mode: one
    selector:
      pods:
        default:
        - dm-master-0
        - dm-master-1
        - dm-master-2
        - dm-worker-0
        - dm-worker-1
        - dm-worker-2
        - dm-worker-3
    volumePath: /data
    path: /data/**/*
    delay: 100ms
    percent: 50
    duration: 60s
