apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: network-loss-dm
  labels:
    app: network-loss-dm
spec:
  schedule: 2-59/5 * * * *
  type: NetworkChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  networkChaos:
    action: loss
    mode: one
    selector:
      pods:
        default:
        - dm-master-0
        - dm-master-1
        - dm-master-2
        - dm-worker-0
        - dm-worker-1
        - dm-worker-2
        - dm-worker-3
    loss:
      loss: "25"
      correlation: "25"
    duration: 30s
