name: "\U0001F41B Bug Report"
description: File a bug report
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please answer these questions before submitting your issue. Thanks!
  - type: textarea
    id: problem
    attributes:
      label: What did you do?
      description: If possible, provide a recipe for reproducing the error.
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: see
    attributes:
      label: What did you see instead?
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Versions of the cluster
      value: |-
             Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

             ```console
             (paste TiDB cluster version here)
             ```

             TiCDC version (execute `cdc version`):

             ```console
             (paste TiCDC version here)
             ```
    validations:
      required: true
