name: "\U0001F41B Dataflow Engine Bug Report"
description: Something isn't working as expected
labels: ["type/bug","area/engine"]
body:
  - type: markdown
    attributes:
      value: |
        Please answer these questions before submitting your issue. Thanks!
  - type: textarea
    id: problem
    attributes:
      label: What did you do?
      description: If possible, provide a recipe for reproducing the error.
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: What did you expect to see?
    validations:
      required: false
  - type: textarea
    id: see
    attributes:
      label: What did you see instead?
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Versions of the cluster
      value: |-
             Dataflow Engine version (run `df-master -V` or `df-executor -V`):

             ```console
             (paste Dataflow Engine version here)
             ```
    validations:
      required: true
