[sink]
transaction-atomicity = ""

[sink.csv]
# delimiter between fields. Must be ASCII characters. The default value is ','.
delimiter = ','
# Quoting delimiter. Empty value means no quoting. The default value is '"'.
quote = '"'
# Line terminator. Empty value means "\r\n" (CRLF) is line terminators. The default value is empty.
terminator = ''
# Representation of null values in CSV files, the default value is '\N'
null = '\N'
# Directory date separator, Optional values are `none`, `year`, `month`, `date`. The default value is none.
date-separator = 'day'
# Include commit-ts in the row data. The default value is false.
include-commit-ts = false
