version: '2.3'

services:
  frame_mysql_standalone:
    image: mysql:5.7
    platform: linux/amd64
    container_name: frame_mysql_standalone
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
       - '/tmp/dataflow/mysql:/var/lib/mysql'
       - './config/mysql_meta.cnf:/etc/my.cnf'
    ports:
      - "3336:3306"
  user_etcd_standalone:
    image: quay.io/coreos/etcd
    container_name: user_etcd_standalone
    command: etcd -name user_etcd_standalone -advertise-client-urls http://0.0.0.0:2479 -listen-client-urls http://0.0.0.0:2479 -listen-peer-urls http://0.0.0.0:2480 -initial-cluster-token etcd-cluster -initial-cluster "user_etcd_standalone=http://user_etcd_standalone:2480" -initial-cluster-state new
    ports:
      - "12479:2479"
      - "12480:2480"
