@startuml
actor       masterA
entity      workerA
entity      workerB
collections executors
actor       masterB
database    metastore
control     serverMaster
masterA ->o metastore : register itself
masterA -> metastore : request config & status
activate metastore
masterA <-- metastore : response config & status
deactivate metastore
masterA -> serverMaster : request executor resources
activate serverMaster
masterA <-- serverMaster : response executor quota
deactivate serverMaster
masterA -> executors : request launch workerA
activate executors
create workerA
workerA o<-[#0000FF] executors: launched
masterA <-- executors : response launch workerA
deactivate executors
masterA -> executors : request launch workerB
activate executors
create workerB
workerB o<-[#0000FF] executors: launched
masterA <-- executors : response launch workerB
deactivate executors
masterA <-- workerA : heartbeat PING
masterA -> workerA : heartbeat PONG
masterA <-- workerB : heartbeat PING
masterA -> workerB : heartbeat PONG
destroy masterA

create masterB
serverMaster -> masterB : trigger failover
masterB ->o metastore : register itself
masterB -> metastore : request config & status
activate metastore
masterB <-- metastore : response config & status
deactivate metastore
activate masterB
masterB -> masterB : wait to be contacted by workers

workerA -> metastore : find Master
activate metastore
workerA <-- metastore : found Master
deactivate metastore
workerB -> metastore : find Master
activate metastore
workerB <-- metastore : found Master
deactivate metastore
workerA --> masterB : heartbeat PING & update status
workerA <- masterB : heartbeat PONG
workerB --> masterB : heartbeat PING & update status
workerB <- masterB : heartbeat PONG
deactivate masterB
@enduml
