version: "2.3"
services:
        server-master-0:
                image: dataflow:test
                ports:
                        - "10245:10240"
                volumes:
                        - ./config/master.toml:/config.toml
                command:
                        - "./bin/master"
                        - "--name"
                        - "master0"
                        - "--config"
                        - "/config.toml"
                        - "--master-addr"
                        - "0.0.0.0:10240"
                        - "--advertise-addr"
                        - "server-master-0:10240"
                        - "--peer-urls"
                        - "http://0.0.0.0:8291"
                        - "--advertise-peer-urls"
                        - "http://server-master-0:8291"
                        - "--initial-cluster"
                        - "master0=http://server-master-0:8291,master1=http://server-master-1:8291,master2=http://server-master-2:8291"
                        - "--frame-meta-endpoints"
                        - "frame-etcd-standalone:2379"
                        - "--user-meta-endpoints"
                        - "user-etcd-standalone:2379"
                depends_on:
                        - "frame-etcd-standalone"
                        - "user-etcd-standalone"
        server-master-1:
                image: dataflow:test
                ports:
                        - "10246:10240"
                volumes:
                        - ./config/master.toml:/config.toml
                command:
                        - "./bin/master"
                        - "--name"
                        - "master1"
                        - "--config"
                        - "/config.toml"
                        - "--master-addr"
                        - "0.0.0.0:10240"
                        - "--advertise-addr"
                        - "server-master-1:10240"
                        - "--peer-urls"
                        - "http://0.0.0.0:8291"
                        - "--advertise-peer-urls"
                        - "http://server-master-1:8291"
                        - "--initial-cluster"
                        - "master0=http://server-master-0:8291,master1=http://server-master-1:8291,master2=http://server-master-2:8291"
                        - "--frame-meta-endpoints"
                        - "frame-etcd-standalone:2379"
                        - "--user-meta-endpoints"
                        - "user-etcd-standalone:2379"
                depends_on:
                        - "frame-etcd-standalone"
                        - "user-etcd-standalone"
        server-master-2:
                image: dataflow:test
                ports:
                        - "10247:10240"
                volumes:
                        - ./config/master.toml:/config.toml
                command:
                        - "./bin/master"
                        - "--name"
                        - "master2"
                        - "--config"
                        - "/config.toml"
                        - "--master-addr"
                        - "0.0.0.0:10240"
                        - "--advertise-addr"
                        - "server-master-2:10240"
                        - "--peer-urls"
                        - "http://0.0.0.0:8291"
                        - "--advertise-peer-urls"
                        - "http://server-master-2:8291"
                        - "--initial-cluster"
                        - "master0=http://server-master-0:8291,master1=http://server-master-1:8291,master2=http://server-master-2:8291"
                        - "--frame-meta-endpoints"
                        - "frame-etcd-standalone:2379"
                        - "--user-meta-endpoints"
                        - "user-etcd-standalone:2379"
                depends_on:
                        - "frame-etcd-standalone"
                        - "user-etcd-standalone"
        server-executor-0:
                image: dataflow:test
                volumes:
                        - ./config/executor.toml:/config.toml
                        - /tmp/dataflow:/tmp/dataflow
                command:
                        - "./bin/executor"
                        - "--config"
                        - "/config.toml"
                        - "--join"
                        - "server-master-0:10240,server-master-1:10240,server-master-2:10240"
                        - "--worker-addr"
                        - "0.0.0.0:10241"
                        - "--advertise-addr"
                        - "server-executor-0:10241"
                depends_on:
                        - "server-master-0"
                        - "server-master-2"
                        - "server-master-1"
                extra_hosts:
                        - "host.docker.internal:host-gateway"
        server-executor-1:
                image: dataflow:test
                volumes:
                        - ./config/executor.toml:/config.toml
                        - /tmp/dataflow:/tmp/dataflow
                command:
                        - "./bin/executor"
                        - "--config"
                        - "/config.toml"
                        - "--join"
                        - "server-master-0:10240,server-master-1:10240,server-master-2:10240"
                        - "--worker-addr"
                        - "0.0.0.0:10241"
                        - "--advertise-addr"
                        - "server-executor-1:10241"
                depends_on:
                        - "server-master-0"
                        - "server-master-2"
                        - "server-master-1"
                extra_hosts:
                        - "host.docker.internal:host-gateway"
        server-executor-2:
                image: dataflow:test
                volumes:
                        - ./config/executor.toml:/config.toml
                        - /tmp/dataflow:/tmp/dataflow
                command:
                        - "./bin/executor"
                        - "--config"
                        - "/config.toml"
                        - "--join"
                        - "server-master-0:10240,server-master-1:10240,server-master-2:10240"
                        - "--worker-addr"
                        - "0.0.0.0:10241"
                        - "--advertise-addr"
                        - "server-executor-2:10241"
                depends_on:
                        - "server-master-0"
                        - "server-master-2"
                        - "server-master-1"
                extra_hosts:
                        - "host.docker.internal:host-gateway"
        frame-etcd-standalone:
                image: quay.io/coreos/etcd
                container_name: frame-etcd-standalone
                volumes:
                        - ./config/etcd.yml:/etcd.yml
                command:
                        - "etcd"
                        - "--config-file"
                        - "/etcd.yml"
                ports:
                        - "12379:2379"
                        - "12380:2380"
        user-etcd-standalone:
                image: quay.io/coreos/etcd
                container_name: user-etcd-standalone
                volumes:
                        - ./config/etcd.yml:/etcd.yml
                command:
                        - "etcd"
                        - "--config-file"
                        - "/etcd.yml"
                ports:
                        - "12479:2379"
                        - "12480:2380"
