version: "2.3"
services:
        demo-server:
                image: dataflow:test
                ports:
                        - "1234:1234"
                command:
                        - ./bin/demoserver
                        - "/data"
                        - "10000"
