#!/bin/bash
# parameter 1: name
# parameter 2: retry count

name1=$1
name2=$2
retry=$3

i=0
while [ $i -lt $retry ]; do
  echo $(ps aux | grep $name1 | grep $name2 | sed '/.*check_process_exit.*/d')
	ret=$(ps aux | grep $name1 | grep $name2 | sed '/.*check_process_exit.*/d' | wc -l)
	if [ $ret -lt 1 ]; then
		break
	fi
	((i++))
	echo "wait for process $name1 $name2 exits the $i-th time"
	sleep 1
done

if [ $i -ge $retry ]; then
	echo " process $name1 $name2 exits timeout"
	exit 1
fi
