@startuml
(*) --> "NewMaster(masterType, config, ...)"
    --> "master.Init(...)"

if "Metastore key exists" then
  -->[true] "wait for worker heartbeats"
  --> "update active worker list"
  -right-> "init finished"
else
  ->[false] "verify and fix config"
  -->[update metastore] "init finished"
endif
@enduml

