@startuml
state c <<choice>>
[*] --> c
c --> workerEntryCreated: New
c --> workerEntryWait: Failover

workerEntryCreated: ExpireAt = time.Now() + delta
workerEntryWait: ExpireAt is unset while waiting for heartbeat.

workerEntryCreated --> workerEntryNormal: Heartbeat
workerEntryWait --> workerEntryNormal: Heartbeat

workerEntryNormal: ExpireAt = time.Now() + delta
workerEntryNormal --> workerEntryNormal: Heartbeat

workerEntryOffline: worker is considered dead.
workerEntryNormal --> workerEntryOffline: ExpireAt is reached
workerEntryCreated --> workerEntryOffline: ExpireAt is reached

workerEntryTombstone: Worker is dead and the business \nlogic can remove meta.
workerEntryOffline --> workerEntryTombstone: OnWorkerOffline callback is run.
workerEntryWait --> workerEntryTombstone: Delta passed after failover.
@enduml