
# 指定配置文件中涉及的库名、表名是否为大小写敏感的
# 该配置会同时影响 filter 和 sink 相关配置，默认为 true
case-sensitive = true

[filter]
# 忽略哪些 CommitTS 的事务
ignore-txn-commit-ts = [1, 2]

# 同步哪些库
do-dbs = ["test1", "sys1"]

# 同步哪些表
do-tables = [
	{db-name = "test", tbl-name = "tbl1"},
	{db-name = "test", tbl-name = "tbl2"},
]

# 忽略哪些库
ignore-dbs = ["test", "sys"]

# 忽略哪些表
ignore-tables = [
	{db-name = "test", tbl-name = "tbl3"},
	{db-name = "test", tbl-name = "tbl4"},
]

[mounter]
# mounter 线程数
worker-num = 64

[sink]
# 对于 MQ 类的 Sink，可以通过 dispatch-rules 配置 event 分发规则
# 分发规则支持 default, ts, rowid, table
dispatch-rules = [
	{db-name = "test", tbl-name = "tbl3", rule = "ts"},
	{db-name = "test", tbl-name = "tbl4", rule = "rowid"},
]

[cyclic-replication]
# 是否开启环形复制
enable = true
# 当前 CDC 的复制 ID
replica-id = 1
# 需要过滤掉的复制 ID
filter-replica-ids = [2,3]
# 是否同步 DDL
sync-ddl = true
