{
 "title": "DM-Monitor-Professional",
 "time": { "from": "2022-05-24T06:39:33.372Z", "to": "2022-05-24T10:39:33.372Z" },
 "templating": {
  "list": [
   {
    "name": "task",
    "label": "Task",
    "query": {
     "query": "label_values(dm_worker_task_state, task)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(dm_worker_task_state, source_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dm_worker_task_state{task=~\"$task\"}, instance)"
    }
   },
   {
    "name": "queueNo",
    "label": "Queue",
    "query": {
     "query": "label_values(dm_syncer_finished_jobs_total, queueNo)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(dm_syncer_finished_jobs_total,type)"
    }
   },
   {
    "name": "stage",
    "label": "Stage",
    "query": {
     "query": "label_values(dm_syncer_binlog_transform_cost_count,stage)"
    }
   },
   {
    "name": "target_schema",
    "label": "Target Schema",
    "query": {
     "query": "label_values(dm_syncer_finished_jobs_total, target_schema)"
    }
   },
   {
    "name": "target_table",
    "label": "Target_table",
    "query": {
     "query": "label_values(dm_syncer_finished_jobs_total, target_table)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(dm_syncer_finished_jobs_total,worker)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "dump and load ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "dump progress",
     "type": "graph",
     "description": "The data import process percentage of Dumpling. The value is an estimated value and may exceed less than 100%.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "dumpling_dump_finished_rows{task=~\"$task\",source_id=~\"$source\"} / dumpling_dump_estimate_total_rows{task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "load progress",
     "type": "graph",
     "description": "The data import process percentage of Loader. The value range is 0% ~ 100%",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "dm_loader_progress{task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "remaining time to loader",
     "type": "graph",
     "description": "The predicted remaining time it takes Syncer to be completely synchronized with the master (in seconds)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (task,source_id) (dm_loader_remaining_time{task=~\"$task\", source_id=~\"$source\"})",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "dump process exits with error",
     "type": "graph",
     "description": "Dumper encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(dm_dumpling_exit_with_error_count{task=~\"$task\",source_id=~\"$source\"}[30m])",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "load process exits with error",
     "type": "graph",
     "description": "Loader encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(dm_loader_exit_with_error_count{task=~\"$task\",source_id=~\"$source\"}[30m])",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "statement execution latency - 90",
     "type": "graph",
     "description": "The time it takes loader to execute every statement to the downstream (in seconds)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_stmt_duration_time_bucket{task=~\"$task\", type=\"begin\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "begin"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_stmt_duration_time_bucket{task=~\"$task\", type=\"stmt\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "stmt"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_stmt_duration_time_bucket{task=~\"$task\", type=\"commit\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "commit"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_stmt_duration_time_bucket{task=~\"$task\", type=\"rollback\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "rollback"
      }
     ]
    },
    {
     "title": "transaction execution QPS",
     "type": "graph",
     "description": "number of sql executed per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dm_loader_txn_duration_time_count{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le,worker,task,target_schema,target_table)",
       "legendFormat": "{{worker}}-{{task}}-{{target_schema}}-{{target_table}}"
      }
     ]
    },
    {
     "title": "transaction execution latency",
     "type": "graph",
     "description": "The duration that Loader executes a transaction (in seconds)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_txn_duration_time_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_loader_txn_duration_time_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_loader_txn_duration_time_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "table count",
     "type": "graph",
     "description": "The total number of tables in the full data imported by Loader",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_loader_table_gauge{task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "data file count",
     "type": "graph",
     "description": "The total number of data files in the full data imported by Loader (including the `INSERT INTO` statement)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_loader_data_file_gauge{task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "data file size",
     "type": "graph",
     "description": "The total size of the data files in the full data imported by Loader (including the `INSERT INTO` statement)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dm_loader_data_size_gauge{task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "binlog replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication QPS",
     "type": "graph",
     "description": "number of sql executed per second(one minute average value, dm_syncer_finished_jobs_total )",
     "gridPos": { "h": 12, "w": 15, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dm_syncer_finished_jobs_total{task=~\"$task\", source_id=~\"$source\",target_schema=~\"$target_schema\",type=~\"$type\"}[$interval]))by (task,source_id,target_schema,type)",
       "legendFormat": "{{task}} - {{target_schema}} -  {{type}} "
      }
     ]
    },
    {
     "title": "Remaining time to sync",
     "type": "graph",
     "description": "The predicted remaining time it takes Syncer to be completely synchronized with the master (in seconds)",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_remaining_time{task=~\"$task\",source_id=~\"$source\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "Replication lag",
     "type": "graph",
     "description": "The latency time it takes to replicate the binlog from master to Syncer (in seconds)",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_replication_lag_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,source_id,task))",
       "legendFormat": "{{task}} - {{source_id}} - 90"
      },
      {
       "expr": "dm_syncer_replication_lag_gauge{instance=~\"$instance\",task=~\"$task\"}",
       "legendFormat": "{{task}} - {{source_id}} - gauge"
      }
     ]
    },
    {
     "title": "Replication QPS (Sum by task)",
     "type": "graph",
     "description": "number of sql executed per second(one minute average value, dm_syncer_finished_jobs_total )\n\nThe maximum TPS estimated according to the recent SQL time-consuming, may vary greatly with different SQL",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dm_syncer_finished_jobs_total{task=~\"$task\"}[$interval])) by (task)",
       "legendFormat": "{{task}} "
      },
      {
       "expr": "sum(dm_syncer_ideal_qps{task=~\"$task\"}) by (task)",
       "legendFormat": "{{task}} - ideal"
      }
     ]
    },
    {
     "title": "process exits with error",
     "type": "graph",
     "description": "The binlog replication unit process encounters an error within the DM-worker and exits",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(dm_syncer_exit_with_error_count{task=~\"$task\", source_id=~\"$source\"}[30m])",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "DM SQL jobs ",
     "type": "graph",
     "description": "The number of add/finished jobs per unit of time",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dm_syncer_finished_jobs_total{task=~\"$task\", source_id=~\"$source\",target_schema=~\"$target_schema\",type=~\"$type\"}[$interval])) by (task,source_id,target_schema,type)",
       "legendFormat": "finished-{{task}} - {{target_schema}} - {{type}} "
      },
      {
       "expr": "sum(-rate(dm_syncer_added_jobs_total{task=~\"$task\", source_id=~\"$source\",target_schema=~\"$target_schema\",type=~\"$type\"}[$interval])) by (task,source_id,target_schema,type)",
       "legendFormat": "add-{{task}} - {{target_schema}} - {{type}}"
      }
     ]
    },
    {
     "title": "DML conflict detect duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to detect conflicts between DMLs (in seconds)",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_conflict_detect_duration_bucket{task=~\"$task\"}[$interval])) by (le,task))",
       "legendFormat": "{{task}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_conflict_detect_duration_bucket{task=~\"$task\"}[$interval])) by (le,task))",
       "legendFormat": "{{task}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_conflict_detect_duration_bucket{task=~\"$task\"}[$interval])) by (le,task))",
       "legendFormat": "{{task}} - 99"
      }
     ]
    },
    {
     "title": "binlog event QPS",
     "type": "graph",
     "description": "The number of binlog events received per unit of time (this number does not include the events that need to be skipped)",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,task,stage) (rate(dm_syncer_binlog_transform_cost_count{instance=~\"$instance\",task=~\"$task\", source_id=~\"$source\",stage=~\"$stage\"}[$interval]))",
       "legendFormat": "{{task}} - {{instance}} - {{stage}}"
      }
     ]
    },
    {
     "title": "add job duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to add a job to the queue (in seconds)",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum (rate(dm_syncer_add_job_duration_bucket{task=~\"$task\", source_id=~\"$source\",queueNo=~\"$queueNo\",type=~\"$type\"}[$interval])) by (task,le))",
       "legendFormat": "{{task}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_add_job_duration_bucket{task=~\"$task\", source_id=~\"$source\",queueNo=~\"$queueNo\",type=~\"$type\"}[$interval])) by (task,le))",
       "legendFormat": "{{task}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_add_job_duration_bucket{task=~\"$task\", source_id=~\"$source\",queueNo=~\"$queueNo\",type=~\"$type\"}[$interval])) by (task,le))",
       "legendFormat": "{{task}}  - 99"
      }
     ]
    },
    {
     "title": "transaction/ddl query execution latency",
     "type": "graph",
     "description": "The time it takes binlog replication unit to execute the transaction to the downstream (in seconds)",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_txn_duration_time_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - txn-90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_txn_duration_time_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - txn-95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_txn_duration_time_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - txn-99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_query_duration_time_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - ddl-90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_query_duration_time_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - ddl-95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_query_duration_time_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{instance}} - ddl-99"
      }
     ]
    },
    {
     "title": "statement execution latency - 90",
     "type": "graph",
     "description": "The time it takes binlog replication unit to execute every statement to the downstream (in seconds)",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{task=~\"$task\", type=\"begin\", instance=~\"$instance\"}[$interval])) by (le,task,instance))",
       "legendFormat": "{{task}} - {{instance}} - begin"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{task=~\"$task\", type=\"stmt\", instance=~\"$instance\"}[$interval])) by (le,task,instance))",
       "legendFormat": "{{task}} - {{instance}} - stmt"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{task=~\"$task\", type=\"commit\", instance=~\"$instance\"}[$interval])) by (le,task,instance))",
       "legendFormat": "{{task}} - {{instance}} - commit"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{task=~\"$task\", type=\"rollback\", instance=~\"$instance\"}[1m])) by (le,task,instance))",
       "legendFormat": "{{task}} - {{instance}} - rollback"
      }
     ]
    },
    {
     "title": "skipped binlog event QPS",
     "type": "graph",
     "description": "The number of binlog events received per unit of time that needs to be skipped",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dm_syncer_skip_binlog_duration_count{task=~\"$task\", source_id=~\"$source\", type=\"rows\"}[$interval])",
       "legendFormat": "{{task}} - {{source_id}} - rows"
      },
      {
       "expr": "rate(dm_syncer_skip_binlog_duration_count{task=~\"$task\", source_id=~\"$source\", type=\"query\"}[$interval])",
       "legendFormat": "{{task}} - {{source_id}} - query"
      }
     ]
    },
    {
     "title": "DML queue remain length",
     "type": "graph",
     "description": "The remain length of DML job queues",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dm_syncer_queue_size{task=~\"$task\"}) by (task)",
       "legendFormat": "{{task}}"
      }
     ]
    },
    {
     "title": "binlog event size",
     "type": "graph",
     "description": "The size of a single binlog event that the binlog replication unit reads from relay log or upstream master",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_event_size_bucket{worker=\"$worker\",task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,worker,task))",
       "legendFormat": "{{task}} - {{worker}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_binlog_event_size_bucket{worker=\"$worker\",task=~\"$task\", source_id=~\"$source\"}[1m])) by (le,worker,task))",
       "legendFormat": "{{task}} - {{worker}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_binlog_event_size_bucket{worker=\"$worker\",task=~\"$task\", source_id=~\"$source\"}[1m])) by (le,worker,task))",
       "legendFormat": "{{task}} - {{worker}} - 99"
      }
     ]
    },
    {
     "title": "binlog file gap between master and syncer",
     "type": "graph",
     "description": "The number of binlog files in binlog replication unit that are behind the master",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_binlog_file{source_id=~\"$source\", task=~\"$task\", node=\"master\"} - ON(task,source_id) dm_syncer_binlog_file{source_id=~\"$source\", task=~\"$task\", node=\"syncer\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "binlog event row number",
     "type": "graph",
     "description": "The number of rows of each binlog event that enters the DM",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_event_row_bucket{task=~\"$task\",source_id=~\"$source\"}[$interval])) by (le,task,source))",
       "legendFormat": "{{task}}-{{source}}"
      }
     ]
    },
    {
     "title": "read binlog event duration",
     "type": "graph",
     "description": "The duration that the binlog replication unit reads binlog event from the relay log or upstream MySQL (in seconds)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_read_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_read_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_read_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 99"
      }
     ]
    },
    {
     "title": "binlog event cost duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to parse and transform the binlog into SQL statements (in seconds)",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 69 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_transform_cost_bucket{worker=~\"$worker\",task=~\"$task\", source_id=~\"$source\"}[1m])) by (le,worker,task,stage))",
       "legendFormat": "90-[[worker]]-[[task]]-{{stage}}"
      }
     ]
    },
    {
     "title": "dispatch binlog event duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to dispatch a binlog event (in seconds)",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 69 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_dispatch_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_dispatch_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_dispatch_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 99"
      }
     ]
    },
    {
     "title": "unsynced tables",
     "type": "graph",
     "description": "The number of unsynced tables in the subtask",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_unsynced_table_number{source_id=~\"$source\", task=~\"$task\"}",
       "legendFormat": "{{task}} - {{source_id}}"
      }
     ]
    },
    {
     "title": "binlog file gap between relay and syncer",
     "type": "graph",
     "description": "The number of binlog files in binlog replication unit that are behind relay",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{instance=~\"$instance\", node=\"relay\"} - ON(instance) group_right dm_syncer_binlog_file{instance=~\"$instance\", task=~\"$task\", node=\"syncer\"}",
       "legendFormat": "{{instance}} - {{task}}"
      }
     ]
    },
    {
     "title": "Flushed Checkpoint Time Interval",
     "type": "graph",
     "description": "The time interval of DM written to disk",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_flush_checkpoints_time_interval_bucket{task=~\"$task\"}[$interval])) by (le,task,worker))",
       "legendFormat": "{{task}}-{{worker}}"
      }
     ]
    },
    {
     "title": "shard lock resolving",
     "type": "graph",
     "description": "Is waiting shard DDL lock to be resolved, >0 means waiting",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_shard_lock_resolving{source_id=~\"$source\", task=~\"$task\"}",
       "legendFormat": "{{task}} - {{source}}"
      }
     ]
    },
    {
     "title": "skip event duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to skip a binlog event (in seconds)",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 85 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_skip_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_skip_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_skip_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[$interval])) by (le,task,source_id))",
       "legendFormat": "{{task}} - {{source_id}} - 99"
      }
     ]
    },
    {
     "title": "replication transaction batch",
     "type": "graph",
     "description": "Display the number of sql contained in the dm copy incremental data to the downstream transaction from each latitude",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_replication_transaction_batch_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task,queueNo,type))",
       "legendFormat": "{{task}} - {{queueNo}} - {{type}}"
      }
     ]
    },
    {
     "title": " transform binlog event duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_transform_cost_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{source_id}} - {{instance}} -  90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_binlog_transform_cost_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{source_id}} - {{instance}} -  95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_binlog_transform_cost_bucket{instance=~\"$instance\",task=~\"$task\"}[$interval])) by (le,instance,task))",
       "legendFormat": "{{task}} - {{source_id}} - {{instance}} -  99"
      }
     ]
    }
   ]
  },
  {
   "title": "Incremental Validation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "validator binlog file",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_validator_validator_binlog_file"
      }
     ]
    },
    {
     "title": "validator binlog position",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_validator_validator_binlog_pos"
      }
     ]
    },
    {
     "title": "validation error count",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_validator_validator_error_count"
      }
     ]
    },
    {
     "title": "validator binlog latency(in byte offset)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_validator_validator_logpos_latency"
      }
     ]
    },
    {
     "title": "validator binlog latency (in file)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_validator_validator_logfile_latency"
      }
     ]
    }
   ]
  },
  {
   "title": "relay log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "storage capacity",
     "type": "graph",
     "description": "The storage capacity of the disk occupied by the relay log",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dm_relay_space{instance=~\"$instance\", type=\"capacity\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "storage remain",
     "type": "graph",
     "description": "The remaining storage capacity of the disk occupied by the relay log",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dm_relay_space{instance=~\"$instance\", type=\"available\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process exits with error",
     "type": "graph",
     "description": "The relay log encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_exit_with_error_count{instance=~\"$instance\"}",
       "legendFormat": " {{instance}}"
      }
     ]
    },
    {
     "title": "relay log data corruption",
     "type": "graph",
     "description": "The number of corrupted relay log files",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_data_corruption{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fail to read binlog from master",
     "type": "graph",
     "description": "The number of errors encountered when the relay log reads the binlog from the upstream MySQL",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_read_error_count{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fail to write relay log",
     "type": "graph",
     "description": "The number of errors encountered when the relay log writes the binlog to disks",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_write_error_count{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "binlog file index",
     "type": "graph",
     "description": "The largest index number of relay log files. E.g. \"value = 1\" indicates \"mysql-bin.000001\"",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{instance=~\"$instance\", node=\"master\"}",
       "legendFormat": "master"
      },
      {
       "expr": "dm_relay_binlog_file{instance=~\"$instance\", node=\"relay\"}",
       "legendFormat": "relay"
      }
     ]
    },
    {
     "title": "binlog file gap between master and relay",
     "type": "graph",
     "description": "The number of binlog files in the relay log that are behind the upstream master",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{instance=~\"$instance\", node=\"master\"} - ON(instance) dm_relay_binlog_file{instance=~\"$instance\", node=\"relay\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "binlog pos",
     "type": "graph",
     "description": "The write offset of the latest relay log file",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_pos{instance=~\"$instance\", node=\"master\"}",
       "legendFormat": "master - {{instance}}"
      },
      {
       "expr": "dm_relay_binlog_pos{instance=~\"$instance\", node=\"relay\"}",
       "legendFormat": "relay - {{instance}}"
      }
     ]
    },
    {
     "title": "read binlog event duration",
     "type": "graph",
     "description": "The duration that the relay log reads binlog event from the upstream MySQL (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_relay_read_binlog_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_relay_read_binlog_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_relay_read_binlog_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "write relay log duration",
     "type": "graph",
     "description": "The duration that the relay log writes binlog event into the disks each time (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_relay_write_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_relay_write_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_relay_write_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "binlog event size",
     "type": "graph",
     "description": "The size of a single binlog event that the relay log writes into the disks",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_relay_write_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_relay_write_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_relay_write_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    }
   ]
  },
  {
   "title": "HA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "number of dm-masters start leader components per minute",
     "type": "graph",
     "description": "number of dm-masters try to start leader components per minute",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "dm_master_start_leader_counter", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "number of workers in different state",
     "type": "graph",
     "description": "number of worker in different states, -1 - unrecognized, 0 - offline, 1 - free, 2 - bound",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_values(\"state\", dm_master_worker_state)"
      }
     ]
    },
    {
     "title": "workers' state",
     "type": "graph",
     "description": "state of worker, -1 - unrecognized, 0 - offline, 1 - free, 2 - bound",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (dm_master_worker_state)"
      }
     ]
    },
    {
     "title": "number of worker event error",
     "type": "graph",
     "description": "number of worker event error",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (dm_master_worker_event_error)"
      }
     ]
    },
    {
     "title": "shard ddl error per minute",
     "type": "graph",
     "description": "number of shard DDL lock/operation error in one minute",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (task, type) (increase(dm_master_shard_ddl_error[1m]))"
      }
     ]
    },
    {
     "title": "number of pending shard ddl",
     "type": "graph",
     "description": "number of pending shard DDL in different states, Un-synced (waiting all upstream), Synced (all upstream finished, waiting all downstream)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (task, type) (dm_master_ddl_state_number)"
      }
     ]
    }
   ]
  },
  {
   "title": "operate error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "before any operate error",
     "type": "graph",
     "description": "The number of error happens before operate",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"BeforeAnyOp\"}"
      }
     ]
    },
    {
     "title": "source bound error",
     "type": "graph",
     "description": "The number of error happens in operate source bound",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"SourceBound\"}"
      }
     ]
    },
    {
     "title": "start error",
     "type": "graph",
     "description": "The number of error happens in operate start",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"Start\"}"
      }
     ]
    },
    {
     "title": "pause error",
     "type": "graph",
     "description": "The number of error happens in operate pause",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"Pause\"}"
      }
     ]
    },
    {
     "title": "resume error",
     "type": "graph",
     "description": "The number of error happens in operate resume",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"Resume\"}"
      }
     ]
    },
    {
     "title": "auto-resume error",
     "type": "graph",
     "description": "The number of error happens in operate auto-resume",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"AutoResume\"}"
      }
     ]
    },
    {
     "title": "update error",
     "type": "graph",
     "description": "The number of error happens in operate update",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"Update\"}"
      }
     ]
    },
    {
     "title": "stop error",
     "type": "graph",
     "description": "The number of error happens in operate stop",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"Stop\"}"
      }
     ]
    }
   ]
  }
 ]
}