CREATE TABLE t1 (
  PK INT PRIMARY KEY,
  COL INT
);

CREATE DATABASE foo;
USE foo;

CREATE TABLE bar (
  PK INT PRIMARY KEY,
  COL INT
);
INSERT INTO bar VALUES (1, 1);

/* VIEW */
CREATE VIEW V1 AS 
SELECT *
FROM bar
WHERE COL > 2;
DROP VIEW IF EXISTS V1;

/* ALTER COLUMN */
ALTER TABLE bar
ADD COLUMN COL2 INT;
ALTER TABLE bar
MODIFY COLUMN COL2 FLOAT;
ALTER TABLE bar
DROP COLUMN COL2;

/* Rebase AutoID */
ALTER TABLE t2 AUTO_INCREMENT=310;

/* Set DEFAULT value */
ALTER TABLE bar
ALTER COL SET DEFAULT 3;

/* Modify TABLE comment */
ALTER TABLE bar COMMENT = 'New table comment';

/* Modify TABLE charset */
ALTER TABLE t1 CHARACTER SET = utf8mb4 COLLATE utf8mb4_unicode_ci;

/* Modify DATABASE charset */
ALTER DATABASE foo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

/* TTL */
CREATE TABLE t1 (
  PK INT PRIMARY KEY,
  COL INT
) TTL = `created_at` + INTERVAL 3 MONTH;
ALTER TABLE t1 TTL = `created_at` + INTERVAL 1 MONTH;
ALTER TABLE t1 TTL_ENABLE = 'OFF';
ALTER TABLE t1 REMOVE TTL;

/* MultiSchemaChange */
ALTER TABLE test.t1 
CHANGE COL COL2 VARCHAR(255);
ALTER TABLE for.t1 
CHANGE COL COL2 VARCHAR(255);

/* PARTITION */
CREATE TABLE t2 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    year_col INT
)
PARTITION BY RANGE (year_col) (
    PARTITION p0 VALUES LESS THAN (1991),
    PARTITION p1 VALUES LESS THAN (1995),
    PARTITION p2 VALUES LESS THAN (1999)
);
ALTER TABLE t2 ADD PARTITION (PARTITION p3 VALUES LESS THAN (2002));
ALTER TABLE t2 REORGANIZE PARTITION n0 INTO (
    PARTITION p0 VALUES LESS THAN (1991),
    PARTITION p3 VALUES LESS THAN (2002)
);
ALTER TABLE t2 TRUNCATE PARTITION p0;
ALTER TABLE t2 DROP PARTITION p0, p1;

/* EXCHANGE PARTITION */
CREATE TABLE e (
    id INT NOT NULL,
    fname VARCHAR(30),
    lname VARCHAR(30)
)
    PARTITION BY RANGE (id) (
        PARTITION p0 VALUES LESS THAN (50),
        PARTITION p1 VALUES LESS THAN (100),
        PARTITION p2 VALUES LESS THAN (150),
        PARTITION p3 VALUES LESS THAN (MAXVALUE)
);
INSERT INTO e VALUES
    (1669, "Jim", "Smith"),
    (337, "Mary", "Jones"),
    (16, "Frank", "White"),
    (2005, "Linda", "Black");
CREATE TABLE e2 LIKE e;
ALTER TABLE e2 REMOVE PARTITIONING;
ALTER TABLE e EXCHANGE PARTITION p0 WITH TABLE e2;

/* ALTER INDEX visibility */
CREATE TABLE t3 (
  i INT,
  j INT,
  k INT,
  INDEX i_idx (i) INVISIBLE
) ENGINE = InnoDB;
CREATE INDEX j_idx ON t3 (j) INVISIBLE;
ALTER TABLE t3 ADD INDEX k_idx (k) INVISIBLE;
ALTER TABLE t1 ALTER INDEX i_idx INVISIBLE;
ALTER TABLE t1 ALTER INDEX i_idx VISIBLE;

/* RENAME TABLE */
RENAME TABLE t3 TO renam_t3;

/* INDEX */
CREATE TABLE t4 (col1 INT, col2 INT, INDEX func_index ((ABS(col1))));
CREATE INDEX idx1 ON t4 ((col1 + col2));
CREATE INDEX idx2 ON t4 ((col1 + col2), (col1 - col2), col1);
DROP INDEX idx1 ON t4;
ALTER TABLE t4 ADD INDEX ((col1 * 40) DESC);
ALTER TABLE t4 RENAME INDEX func_index TO new_func_index;

/* PK */
ALTER TABLE t4 ADD COLUMN `id` INT(10) unsigned primary KEY AUTO_INCREMENT;
ALTER TABLE t4 DROP PRIMARY KEY;

/* DROP and recover */
DROP TABLE t1;
RECOVER TABLE t1;

DROP TABLE IF EXISTS bar;
DROP DATABASE IF EXISTS foo;
