apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tiflow.name" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tiflow.name" . }}-configmap
    app.kubernetes.io/instance: {{ include "tiflow.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: tiflow
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
{{ include "tiflow.configmap.data" . | indent 2}}
