CREATE TABLE GENERATED_TABLE (
  A SMALLINT UNSIGNED,
  B SMALLINT UNSIGNED AS (2 * A),
  C SMALLINT UNSIGNED AS (3 * A) NOT NULL,
  PK INT PRIMARY KEY
);
INSERT INTO GENERATED_TABLE VALUES (15, DEFAULT, DEFAULT, 1);
