/* TiCDC doesn't output generated columns */
-- CREATE TABLE GENERATED_TABLE (
--   id int PRIMARY KEY,
--   A SMALLINT UNSIGNED,
--   B SMALLINT UNSIGNED AS (2 * A),
--   C SMALLINT UNSIGNED AS (3 * A) NOT NULL
-- );
-- INSERT INTO GENERATED_TABLE VALUES (1, 15, DEFAULT, DEFAULT);
