---

# Variables here are applicable to all host groups
deploy_user: "{{ ansible_user }}"
backup_dir: "{{ deploy_dir }}/backup"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
resources_dir: "{{ playbook_dir }}/resources"
binary_dir:    "{{ playbook_dir }}/resources/bin"

# Random shifts for retrying failed ops like downloading
retry_stagger: 5
