apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-dataflow
  labels:
    app: pod-kill-dataflow
spec:
  action: pod-kill
  mode: one
  gracePeriod: 30
  selector:
    pods:
      default: # default namespace
        - server-master-0
        - server-master-1
        - server-master-2
        - executor-0
        - executor-1
        - executor-2
        - executor-3
  scheduler:
    cron: "@every 2m"
