apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-kill-dataflow
  labels:
    app: pod-kill-dataflow
spec:
  schedule: '@every 1m'
  type: PodChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: pod-kill
    mode: one
    gracePeriod: 30
    selector:
      pods:
        default:
        - chaos-server-master-0
        - chaos-server-master-1
        - chaos-server-master-2
        - chaos-executor-0
        - chaos-executor-1
        - chaos-executor-2
        - chaos-executor-3
