apiVersion: v1
kind: Service
metadata:
  name: server-master
  labels:
    app: server-master
spec:
  ports:
    - name: port-master
      port: 10240
      targetPort: 10240
    - name: port-mpeer
      port: 10239
      targetPort: 10239
  selector:
    app: server-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server-master
  labels:
    app: server-master
spec:
  selector:
    matchLabels:
      app: server-master
  serviceName: server-master
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: server-master
    spec:
      containers:
        - name: server-master
          image: dataflow:chaos
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: server-master-data
            - mountPath: /log
              name: server-master-log
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 10240
              name: port-master
            - containerPort: 10239
              name: port-mpeer
          command:
            - "/df-server-master"
            - "--name=$(MY_POD_NAME)"
            - "--master-addr=0.0.0.0:10240"
            - "--advertise-addr=$(MY_POD_NAME).server-master.$(MY_POD_NAMESPACE):10240"
            - "--peer-urls=0.0.0.0:10239"
            - "--advertise-peer-urls=http://$(MY_POD_NAME).server-master.$(MY_POD_NAMESPACE):10239"
            - "--initial-cluster=server-master-0=http://server-master-0.server-master.$(MY_POD_NAMESPACE):10239,server-master-1=http://server-master-1.server-master.$(MY_POD_NAMESPACE):10239,server-master-2=http://server-master-2.server-master.$(MY_POD_NAMESPACE):10239"
            - "--config=/conf/server-master.toml"
  volumeClaimTemplates:
    - metadata:
        name: server-master-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: server-master-log
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
