#!/bin/bash

echo "start deploying engine cluster..."

retry_times=3
i=1
while [ $i -le $retry_times ]; do
	echo "The ${i} times to try to start engine cluster..."

	run_engine.sh deploy $*

	if [ $? -eq 0 ]; then
		break
	fi
	let i++
	echo "start engine cluster failed"
done

if [ $i -gt $retry_times ]; then
	echo -e "\n\n[$(date)] <<<<<< fail to start engine cluster after $retry_times times >>>>>>"
	exit 1
else
	# TODO: add check logic
	# wait cluster ready
	sleep 20
fi
