#!/bin/bash

echo "start deploying dfe cluster..."

retry_times=3
i=1
while [ $i -le $retry_times ]; do
	echo "The ${i} times to try to start dfe cluster..."

	run_dfe.sh deploy $*

	if [ $? -eq 0 ]; then
		break
	fi
	let i++
	echo "start dfe cluster failed"
done

if [ $i -gt $retry_times ]; then
    echo -e "\n\n[$(date)] <<<<<< fail to start dfe cluster after $retry_times times >>>>>>"
    exit 1
else
    # TODO: add check logic
    # wait cluster ready
    sleep 20
fi
