#!/bin/bash

# parameter 1: work directory
# other parameters: config files

set -eu

echo -e "\n\nsave docker compose logs..."
run_engine.sh logs $*
shift

echo "stop engine cluster..."
run_engine.sh stop $*
