#!/bin/bash

# parameter 1: work directory
# other parameters: config files

set -x

echo "save docker compose logs..."
run_engine.sh logs $*
shift

echo "stop engine cluster..."
run_engine.sh stop $*
