// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// get cluster info such as cluster id
	// (GET /api/v1/cluster/info)
	DMAPIGetClusterInfo(c *gin.Context)
	// update cluster info.
	// (PUT /api/v1/cluster/info)
	DMAPIUpdateClusterInfo(c *gin.Context)
	// get cluster master node list
	// (GET /api/v1/cluster/masters)
	DMAPIGetClusterMasterList(c *gin.Context)
	// offline master node
	// (DELETE /api/v1/cluster/masters/{master-name})
	DMAPIOfflineMasterNode(c *gin.Context, masterName string)
	// get cluster worker node list
	// (GET /api/v1/cluster/workers)
	DMAPIGetClusterWorkerList(c *gin.Context)
	// offline worker node
	// (DELETE /api/v1/cluster/workers/{worker-name})
	DMAPIOfflineWorkerNode(c *gin.Context, workerName string)
	// get doc json
	// (GET /api/v1/dm.json)
	GetDocJSON(c *gin.Context)
	// get doc html
	// (GET /api/v1/docs)
	GetDocHTML(c *gin.Context)
	// get data source list
	// (GET /api/v1/sources)
	DMAPIGetSourceList(c *gin.Context, params DMAPIGetSourceListParams)
	// create and enable a new data source
	// (POST /api/v1/sources)
	DMAPICreateSource(c *gin.Context)
	// delete a data source
	// (DELETE /api/v1/sources/{source-name})
	DMAPIDeleteSource(c *gin.Context, sourceName string, params DMAPIDeleteSourceParams)
	// get source
	// (GET /api/v1/sources/{source-name})
	DMAPIGetSource(c *gin.Context, sourceName string, params DMAPIGetSourceParams)
	// update a data source
	// (PUT /api/v1/sources/{source-name})
	DMAPIUpdateSource(c *gin.Context, sourceName string)
	// disable a data source
	// (POST /api/v1/sources/{source-name}/disable)
	DMAPIDisableSource(c *gin.Context, sourceName string)
	// enable a data source
	// (POST /api/v1/sources/{source-name}/enable)
	DMAPIEnableSource(c *gin.Context, sourceName string)
	// disable relay log function for the data source
	// (POST /api/v1/sources/{source-name}/relay/disable)
	DMAPIDisableRelay(c *gin.Context, sourceName string)
	// enable relay log function for the data source
	// (POST /api/v1/sources/{source-name}/relay/enable)
	DMAPIEnableRelay(c *gin.Context, sourceName string)
	// purge relay log
	// (POST /api/v1/sources/{source-name}/relay/purge)
	DMAPIPurgeRelay(c *gin.Context, sourceName string)
	// get source schema list
	// (GET /api/v1/sources/{source-name}/schemas)
	DMAPIGetSourceSchemaList(c *gin.Context, sourceName string)
	// get source table list
	// (GET /api/v1/sources/{source-name}/schemas/{schema-name})
	DMAPIGetSourceTableList(c *gin.Context, sourceName string, schemaName string)
	// get the current status of the data source
	// (GET /api/v1/sources/{source-name}/status)
	DMAPIGetSourceStatus(c *gin.Context, sourceName string)
	// transfer source to a free worker
	// (POST /api/v1/sources/{source-name}/transfer)
	DMAPITransferSource(c *gin.Context, sourceName string)
	// get task list
	// (GET /api/v1/tasks)
	DMAPIGetTaskList(c *gin.Context, params DMAPIGetTaskListParams)
	// create a task
	// (POST /api/v1/tasks)
	DMAPICreateTask(c *gin.Context)
	// Turn task into the format of a configuration file or vice versa.
	// (POST /api/v1/tasks/converters)
	DMAPIConvertTask(c *gin.Context)
	// get task template list
	// (GET /api/v1/tasks/templates)
	DMAPIGetTaskTemplateList(c *gin.Context)
	// create task template
	// (POST /api/v1/tasks/templates)
	DMAPICreateTaskTemplate(c *gin.Context)
	// import task template
	// (POST /api/v1/tasks/templates/import)
	DMAPIImportTaskTemplate(c *gin.Context)
	// delete task template template
	// (DELETE /api/v1/tasks/templates/{task-name})
	DMAPIDeleteTaskTemplate(c *gin.Context, taskName string)
	// get task template template
	// (GET /api/v1/tasks/templates/{task-name})
	DMAPIGetTaskTemplate(c *gin.Context, taskName string)
	// update task template template
	// (PUT /api/v1/tasks/templates/{task-name})
	DMAPUpdateTaskTemplate(c *gin.Context, taskName string)
	// delete a task
	// (DELETE /api/v1/tasks/{task-name})
	DMAPIDeleteTask(c *gin.Context, taskName string, params DMAPIDeleteTaskParams)
	// get a task
	// (GET /api/v1/tasks/{task-name})
	DMAPIGetTask(c *gin.Context, taskName string, params DMAPIGetTaskParams)
	// update a task
	// (PUT /api/v1/tasks/{task-name})
	DMAPIUpdateTask(c *gin.Context, taskName string)
	// get task source table and target table route relation
	// (GET /api/v1/tasks/{task-name}/sources/{source-name}/migrate_targets)
	DMAPIGetTaskMigrateTargets(c *gin.Context, taskName string, sourceName string, params DMAPIGetTaskMigrateTargetsParams)
	// get task source schema list
	// (GET /api/v1/tasks/{task-name}/sources/{source-name}/schemas)
	DMAPIGetSchemaListByTaskAndSource(c *gin.Context, taskName string, sourceName string)
	// get task source table list
	// (GET /api/v1/tasks/{task-name}/sources/{source-name}/schemas/{schema-name})
	DMAPIGetTableListByTaskAndSource(c *gin.Context, taskName string, sourceName string, schemaName string)
	// delete task source table structure
	// (DELETE /api/v1/tasks/{task-name}/sources/{source-name}/schemas/{schema-name}/{table-name})
	DMAPIDeleteTableStructure(c *gin.Context, taskName string, sourceName string, schemaName string, tableName string)
	// get task source table structure
	// (GET /api/v1/tasks/{task-name}/sources/{source-name}/schemas/{schema-name}/{table-name})
	DMAPIGetTableStructure(c *gin.Context, taskName string, sourceName string, schemaName string, tableName string)
	// operate task source table structure
	// (PUT /api/v1/tasks/{task-name}/sources/{source-name}/schemas/{schema-name}/{table-name})
	DMAPIOperateTableStructure(c *gin.Context, taskName string, sourceName string, schemaName string, tableName string)
	// start a task
	// (POST /api/v1/tasks/{task-name}/start)
	DMAPIStartTask(c *gin.Context, taskName string)
	// get task status
	// (GET /api/v1/tasks/{task-name}/status)
	DMAPIGetTaskStatus(c *gin.Context, taskName string, params DMAPIGetTaskStatusParams)
	// stop a task
	// (POST /api/v1/tasks/{task-name}/stop)
	DMAPIStopTask(c *gin.Context, taskName string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(c *gin.Context)

// DMAPIGetClusterInfo operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetClusterInfo(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetClusterInfo(c)
}

// DMAPIUpdateClusterInfo operation middleware
func (siw *ServerInterfaceWrapper) DMAPIUpdateClusterInfo(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIUpdateClusterInfo(c)
}

// DMAPIGetClusterMasterList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetClusterMasterList(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetClusterMasterList(c)
}

// DMAPIOfflineMasterNode operation middleware
func (siw *ServerInterfaceWrapper) DMAPIOfflineMasterNode(c *gin.Context) {
	var err error

	// ------------- Path parameter "master-name" -------------
	var masterName string

	err = runtime.BindStyledParameter("simple", false, "master-name", c.Param("master-name"), &masterName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter master-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIOfflineMasterNode(c, masterName)
}

// DMAPIGetClusterWorkerList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetClusterWorkerList(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetClusterWorkerList(c)
}

// DMAPIOfflineWorkerNode operation middleware
func (siw *ServerInterfaceWrapper) DMAPIOfflineWorkerNode(c *gin.Context) {
	var err error

	// ------------- Path parameter "worker-name" -------------
	var workerName string

	err = runtime.BindStyledParameter("simple", false, "worker-name", c.Param("worker-name"), &workerName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter worker-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIOfflineWorkerNode(c, workerName)
}

// GetDocJSON operation middleware
func (siw *ServerInterfaceWrapper) GetDocJSON(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetDocJSON(c)
}

// GetDocHTML operation middleware
func (siw *ServerInterfaceWrapper) GetDocHTML(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetDocHTML(c)
}

// DMAPIGetSourceList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSourceList(c *gin.Context) {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetSourceListParams

	// ------------- Optional query parameter "with_status" -------------
	if paramValue := c.Query("with_status"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "with_status", c.Request.URL.Query(), &params.WithStatus)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter with_status: %s", err)})
		return
	}

	// ------------- Optional query parameter "enable_relay" -------------
	if paramValue := c.Query("enable_relay"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "enable_relay", c.Request.URL.Query(), &params.EnableRelay)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter enable_relay: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSourceList(c, params)
}

// DMAPICreateSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPICreateSource(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPICreateSource(c)
}

// DMAPIDeleteSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDeleteSource(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIDeleteSourceParams

	// ------------- Optional query parameter "force" -------------
	if paramValue := c.Query("force"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "force", c.Request.URL.Query(), &params.Force)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter force: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDeleteSource(c, sourceName, params)
}

// DMAPIGetSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSource(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetSourceParams

	// ------------- Optional query parameter "with_status" -------------
	if paramValue := c.Query("with_status"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "with_status", c.Request.URL.Query(), &params.WithStatus)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter with_status: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSource(c, sourceName, params)
}

// DMAPIUpdateSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIUpdateSource(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIUpdateSource(c, sourceName)
}

// DMAPIDisableSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDisableSource(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDisableSource(c, sourceName)
}

// DMAPIEnableSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIEnableSource(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIEnableSource(c, sourceName)
}

// DMAPIDisableRelay operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDisableRelay(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDisableRelay(c, sourceName)
}

// DMAPIEnableRelay operation middleware
func (siw *ServerInterfaceWrapper) DMAPIEnableRelay(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIEnableRelay(c, sourceName)
}

// DMAPIPurgeRelay operation middleware
func (siw *ServerInterfaceWrapper) DMAPIPurgeRelay(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIPurgeRelay(c, sourceName)
}

// DMAPIGetSourceSchemaList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSourceSchemaList(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSourceSchemaList(c, sourceName)
}

// DMAPIGetSourceTableList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSourceTableList(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// ------------- Path parameter "schema-name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema-name", c.Param("schema-name"), &schemaName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSourceTableList(c, sourceName, schemaName)
}

// DMAPIGetSourceStatus operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSourceStatus(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSourceStatus(c, sourceName)
}

// DMAPITransferSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPITransferSource(c *gin.Context) {
	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPITransferSource(c, sourceName)
}

// DMAPIGetTaskList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTaskList(c *gin.Context) {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetTaskListParams

	// ------------- Optional query parameter "with_status" -------------
	if paramValue := c.Query("with_status"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "with_status", c.Request.URL.Query(), &params.WithStatus)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter with_status: %s", err)})
		return
	}

	// ------------- Optional query parameter "stage" -------------
	if paramValue := c.Query("stage"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "stage", c.Request.URL.Query(), &params.Stage)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter stage: %s", err)})
		return
	}

	// ------------- Optional query parameter "source_name_list" -------------
	if paramValue := c.Query("source_name_list"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "source_name_list", c.Request.URL.Query(), &params.SourceNameList)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source_name_list: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTaskList(c, params)
}

// DMAPICreateTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPICreateTask(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPICreateTask(c)
}

// DMAPIConvertTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIConvertTask(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIConvertTask(c)
}

// DMAPIGetTaskTemplateList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTaskTemplateList(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTaskTemplateList(c)
}

// DMAPICreateTaskTemplate operation middleware
func (siw *ServerInterfaceWrapper) DMAPICreateTaskTemplate(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPICreateTaskTemplate(c)
}

// DMAPIImportTaskTemplate operation middleware
func (siw *ServerInterfaceWrapper) DMAPIImportTaskTemplate(c *gin.Context) {
	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIImportTaskTemplate(c)
}

// DMAPIDeleteTaskTemplate operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDeleteTaskTemplate(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDeleteTaskTemplate(c, taskName)
}

// DMAPIGetTaskTemplate operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTaskTemplate(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTaskTemplate(c, taskName)
}

// DMAPUpdateTaskTemplate operation middleware
func (siw *ServerInterfaceWrapper) DMAPUpdateTaskTemplate(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPUpdateTaskTemplate(c, taskName)
}

// DMAPIDeleteTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDeleteTask(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIDeleteTaskParams

	// ------------- Optional query parameter "force" -------------
	if paramValue := c.Query("force"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "force", c.Request.URL.Query(), &params.Force)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter force: %s", err)})
		return
	}

	// ------------- Optional query parameter "keep_meta" -------------
	if paramValue := c.Query("keep_meta"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "keep_meta", c.Request.URL.Query(), &params.KeepMeta)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter keep_meta: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDeleteTask(c, taskName, params)
}

// DMAPIGetTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTask(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetTaskParams

	// ------------- Optional query parameter "with_status" -------------
	if paramValue := c.Query("with_status"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "with_status", c.Request.URL.Query(), &params.WithStatus)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter with_status: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTask(c, taskName, params)
}

// DMAPIUpdateTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIUpdateTask(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIUpdateTask(c, taskName)
}

// DMAPIGetTaskMigrateTargets operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTaskMigrateTargets(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetTaskMigrateTargetsParams

	// ------------- Optional query parameter "schema_pattern" -------------
	if paramValue := c.Query("schema_pattern"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "schema_pattern", c.Request.URL.Query(), &params.SchemaPattern)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema_pattern: %s", err)})
		return
	}

	// ------------- Optional query parameter "table_pattern" -------------
	if paramValue := c.Query("table_pattern"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "table_pattern", c.Request.URL.Query(), &params.TablePattern)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter table_pattern: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTaskMigrateTargets(c, taskName, sourceName, params)
}

// DMAPIGetSchemaListByTaskAndSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSchemaListByTaskAndSource(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSchemaListByTaskAndSource(c, taskName, sourceName)
}

// DMAPIGetTableListByTaskAndSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTableListByTaskAndSource(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// ------------- Path parameter "schema-name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema-name", c.Param("schema-name"), &schemaName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTableListByTaskAndSource(c, taskName, sourceName, schemaName)
}

// DMAPIDeleteTableStructure operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDeleteTableStructure(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// ------------- Path parameter "schema-name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema-name", c.Param("schema-name"), &schemaName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema-name: %s", err)})
		return
	}

	// ------------- Path parameter "table-name" -------------
	var tableName string

	err = runtime.BindStyledParameter("simple", false, "table-name", c.Param("table-name"), &tableName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter table-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDeleteTableStructure(c, taskName, sourceName, schemaName, tableName)
}

// DMAPIGetTableStructure operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTableStructure(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// ------------- Path parameter "schema-name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema-name", c.Param("schema-name"), &schemaName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema-name: %s", err)})
		return
	}

	// ------------- Path parameter "table-name" -------------
	var tableName string

	err = runtime.BindStyledParameter("simple", false, "table-name", c.Param("table-name"), &tableName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter table-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTableStructure(c, taskName, sourceName, schemaName, tableName)
}

// DMAPIOperateTableStructure operation middleware
func (siw *ServerInterfaceWrapper) DMAPIOperateTableStructure(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// ------------- Path parameter "schema-name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema-name", c.Param("schema-name"), &schemaName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema-name: %s", err)})
		return
	}

	// ------------- Path parameter "table-name" -------------
	var tableName string

	err = runtime.BindStyledParameter("simple", false, "table-name", c.Param("table-name"), &tableName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter table-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIOperateTableStructure(c, taskName, sourceName, schemaName, tableName)
}

// DMAPIStartTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIStartTask(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIStartTask(c, taskName)
}

// DMAPIGetTaskStatus operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTaskStatus(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetTaskStatusParams

	// ------------- Optional query parameter "source_name_list" -------------
	if paramValue := c.Query("source_name_list"); paramValue != "" {
	}

	err = runtime.BindQueryParameter("form", true, false, "source_name_list", c.Request.URL.Query(), &params.SourceNameList)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source_name_list: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTaskStatus(c, taskName, params)
}

// DMAPIStopTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIStopTask(c *gin.Context) {
	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIStopTask(c, taskName)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	router.GET(options.BaseURL+"/api/v1/cluster/info", wrapper.DMAPIGetClusterInfo)

	router.PUT(options.BaseURL+"/api/v1/cluster/info", wrapper.DMAPIUpdateClusterInfo)

	router.GET(options.BaseURL+"/api/v1/cluster/masters", wrapper.DMAPIGetClusterMasterList)

	router.DELETE(options.BaseURL+"/api/v1/cluster/masters/:master-name", wrapper.DMAPIOfflineMasterNode)

	router.GET(options.BaseURL+"/api/v1/cluster/workers", wrapper.DMAPIGetClusterWorkerList)

	router.DELETE(options.BaseURL+"/api/v1/cluster/workers/:worker-name", wrapper.DMAPIOfflineWorkerNode)

	router.GET(options.BaseURL+"/api/v1/dm.json", wrapper.GetDocJSON)

	router.GET(options.BaseURL+"/api/v1/docs", wrapper.GetDocHTML)

	router.GET(options.BaseURL+"/api/v1/sources", wrapper.DMAPIGetSourceList)

	router.POST(options.BaseURL+"/api/v1/sources", wrapper.DMAPICreateSource)

	router.DELETE(options.BaseURL+"/api/v1/sources/:source-name", wrapper.DMAPIDeleteSource)

	router.GET(options.BaseURL+"/api/v1/sources/:source-name", wrapper.DMAPIGetSource)

	router.PUT(options.BaseURL+"/api/v1/sources/:source-name", wrapper.DMAPIUpdateSource)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/disable", wrapper.DMAPIDisableSource)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/enable", wrapper.DMAPIEnableSource)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/relay/disable", wrapper.DMAPIDisableRelay)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/relay/enable", wrapper.DMAPIEnableRelay)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/relay/purge", wrapper.DMAPIPurgeRelay)

	router.GET(options.BaseURL+"/api/v1/sources/:source-name/schemas", wrapper.DMAPIGetSourceSchemaList)

	router.GET(options.BaseURL+"/api/v1/sources/:source-name/schemas/:schema-name", wrapper.DMAPIGetSourceTableList)

	router.GET(options.BaseURL+"/api/v1/sources/:source-name/status", wrapper.DMAPIGetSourceStatus)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/transfer", wrapper.DMAPITransferSource)

	router.GET(options.BaseURL+"/api/v1/tasks", wrapper.DMAPIGetTaskList)

	router.POST(options.BaseURL+"/api/v1/tasks", wrapper.DMAPICreateTask)

	router.POST(options.BaseURL+"/api/v1/tasks/converters", wrapper.DMAPIConvertTask)

	router.GET(options.BaseURL+"/api/v1/tasks/templates", wrapper.DMAPIGetTaskTemplateList)

	router.POST(options.BaseURL+"/api/v1/tasks/templates", wrapper.DMAPICreateTaskTemplate)

	router.POST(options.BaseURL+"/api/v1/tasks/templates/import", wrapper.DMAPIImportTaskTemplate)

	router.DELETE(options.BaseURL+"/api/v1/tasks/templates/:task-name", wrapper.DMAPIDeleteTaskTemplate)

	router.GET(options.BaseURL+"/api/v1/tasks/templates/:task-name", wrapper.DMAPIGetTaskTemplate)

	router.PUT(options.BaseURL+"/api/v1/tasks/templates/:task-name", wrapper.DMAPUpdateTaskTemplate)

	router.DELETE(options.BaseURL+"/api/v1/tasks/:task-name", wrapper.DMAPIDeleteTask)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name", wrapper.DMAPIGetTask)

	router.PUT(options.BaseURL+"/api/v1/tasks/:task-name", wrapper.DMAPIUpdateTask)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/migrate_targets", wrapper.DMAPIGetTaskMigrateTargets)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/schemas", wrapper.DMAPIGetSchemaListByTaskAndSource)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/schemas/:schema-name", wrapper.DMAPIGetTableListByTaskAndSource)

	router.DELETE(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/schemas/:schema-name/:table-name", wrapper.DMAPIDeleteTableStructure)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/schemas/:schema-name/:table-name", wrapper.DMAPIGetTableStructure)

	router.PUT(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/schemas/:schema-name/:table-name", wrapper.DMAPIOperateTableStructure)

	router.POST(options.BaseURL+"/api/v1/tasks/:task-name/start", wrapper.DMAPIStartTask)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name/status", wrapper.DMAPIGetTaskStatus)

	router.POST(options.BaseURL+"/api/v1/tasks/:task-name/stop", wrapper.DMAPIStopTask)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{
	"H4sIAAAAAAAC/+x9WXfbONbgX8Fo5qFSrdV2NvfphyR2pTPjLCd2TX192vlkiAQltEmAAUC7VDn+79/B",
	"QhIkAZKyLZdVST90OSKWi4u74+Li2yCgSUoJIoIPDr8NeLBCCVR/vooRE+8hgUvEzmhKY7pcy99TRlPE",
	"BEaq1YpyIf+LfodJGqPB4WC293w8HU/Hs8FwINap/IkLhslycDMcpJRVm7+cvtwv2mEi0BKxwc3NcMDQ",
	"1wwzFA4O/60nMZ2/FK3p4j8oEHLUN3HGBWLvofz/JowwDNWvIeIBw6nAlAwO1a+Ic0AjIFYIBBljiAiQ",
	"qEEAoSEaDF3LOnyx98y5NhjjK9Sch5IYEwS4gCIzs2FuprFnECxDxagLSmMEiRw2RjBEDvgxt0dSazBN",
	"ewxKYIKq26aHcSystheqZ77YArqhRnLL5vhJCEpCmyea0ubCavd/GIoGh4P/PSmJdGIodOIkz5vhYMlg",
	"BAnsPc5b3d4eQqOiGGEeY03jWKCEd42nidAezmAEMgbVv1NGEyRWKOO9gfxUdLEHvqbs8tZw/qY6++G8",
	"8W+l7vqn8dmCZiScc5qxAM1zQq7OqT8C+RGo5kBQzS0aZ81pkzX/Go+mbRMKuHRMpYdXHwvm9k2i2rpm",
	"aLKjHqI/O0rUVyF1IcrJn5RcISZpFvLLz+hrhjQVVfdWQH7ZRVJyAEVIkF/OA0oivJxHOHYgTX8E8iPA",
	"BKxhEoOIsgQKsBIi5YeTSUgDPk4xWQYwHQc0mfyxmggcLiZcwEWMJnKSkR4nY1COO5LDjaIsjsdOtHWt",
	"nKeUcPSXXLpNMWo5DkidtMEQFOhUUZCXNDSBdWFID2KJLR/Nj7qJ3szoh/ieSNmFOdekR5jLjfmMYri2",
	"pq3JwUD+IQURFzQFEDDZHDDTfliD0sJSIdi75fkHmKAT2dpJ8EdZkp4qO8QhMgv7JMySFGQEN2FapOo/",
	"mly1vfbsYNA034bKqoyRQOFckWy1W0izRYzKfiRLFrob4gInUKC5oALGc0av+/aMMMF8hcL5Yi3Qxp02",
	"mChldCn1maKkuhzXYDuW7MNUncLs/g4sNtZZX4MbhUO1cxbsLiI+JpvRMGSik4jV1/kCk5gu50uBQyfd",
	"MYHJErw9e3eUGwlZygVDMAG6a0WJopdwFgV7eyMUTF+MZjP0crTYg8FounewB4PZbDqd7h/ORs9fHLwc",
	"DAcki2O5rpopXG5ZBUSPNZGDKOWksil6gKkNigUm46n8315/WEJsrKgIZrEknvFEf9BTVGGTYISYoUBQ",
	"tgbXK8SQAk3vS0yXAHMpcCSB9YBgG1LnmDHKfsNi9R5x7rShJMkoPQaQbNsgI/XrPJDmVKOv+gYCbWo1",
	"BZHumvClr2digOrSOeVAQxseFye9RcJYyu9IRP2GRaAbzV1sYb4BLLetECOZX+L2dSXq7lh9nRZQ7WvT",
	"jo7cdv8KQyhgb4+k6sU7HCcl0Sy52ypFJafI2dsXoen3/hdhXKQtL0LbVPcIfWmkbR9sbYjcK+DGttky",
	"+NI2vEecF67DlkF+j5dMmcZsiQS/R+ArAz/ESu6XcrJFOeZDQH8mFfCpYFkgMob8q9AAzgPl0Mz517jq",
	"LL35fPzq7BicvXp9cgwuxOwC/HSBwwuAifhpNnsCPnw8Ax9+PTkBr349+zh/9+HN5+P3xx/Ohp8+v3v/",
	"6vO/wP87/pfu8QRMfj77X/82ch+Fc0xC9PsX8Obk19Oz48/HR+DnyRNw/OHtuw/H/3hHCD16DY6Of3n1",
	"68kZePPPV59Pj8/+kYnoRbI4AG8+npy8OjvO/y3NKle4wyyt6QGGC2cARlm/jubq91kPj7fono9lYdW5",
	"VbWg4L2Hvfen0+mdw94nFIbd7lxMYXhXd67Fu/J3SpCAxrB2OkvW98I3aGKu293qD1MNvw1fyh7Pmrq6",
	"FAfg2r9ybVEtGnxXOvKF7XvR3Iu9Z7NOnBgu6SK9j8piR+2Bs2CFgss5Q1y5MXUKTRkaqRbAtLC9p/Ij",
	"5iCFnKNwDNyi4S7BnGEVxo6V1iV3p5Os/RoElMzxOslRnPFVxePTzll11N8YFogr306vS4e0EVArSCkm",
	"AnD5CxTg6D0IINGcjwWAkfQkGCr8WNktDwM2job413geUCIQcayNf43BmmbgGhJhrbCydw7NBC6CWama",
	"cu0h1dMQXAR7/k/77k930Ed/dyqkNQmai/01DWGOc5oKnGAucAD4CrJQolHKAantwTUWKx35N1tDSbwG",
	"GUeh9MgJgMaxBTQIMsYBJt4xj45OQFJxZoutqQdBrX1yEa7jzGgbp7d3V2OfMuYKCpQRjECuP0tBSmMc",
	"rEEl8t2MFfyeYmbswJyfpnVmUo10xEFgHc8pprP97VyReOImlrKTf7IrbSgW8+4/mzamPlshkDeWHJQi",
	"hmmIAxjHa2BEXtQM4ehlhUNgBgdXMM7QIVBTSILiKKAk5LeDnqEEYjLnKQxQZQWzp3X432OCkywBEUMI",
	"hJhfAtVLwfD29W2mv/HRxL3G0x8wztcV16vMmaIAR2sDPM8WVjQvogw0wB6DdxEgVADdE0uaUGf/UlQJ",
	"QAkC1ziOwQIpATQGpwpSc8Z0CPYgev7sYP9gFD1/GY1mM/RitAjRXh4+lYbpC72UWXfAsMbpTRy7+F1t",
	"6xvFxE18KI2mj8hypmyyuIpUz/XH0i60dNiPuPNOxZ1vfFTS7d3YYrtKJSaLo3RAqkPUcJgfyGo20Yql",
	"ROpPNazOhmD28vnLJy5mr8zrIT4Xzd2B2NqJyw2CRlyejSEBun8AAiiC1TxL50mRmVUF4nolLRQmhbhq",
	"C7JUG1PF7lhOmI/NnXJ1M/os1z2e8GyhhnSZie4UkByJmiorw33OCJGduyRnlVidRGQv17XDPqTnYLtE",
	"8akyV4vjmyafaXNWyR51HDQsg2rdUZtaIO0UBRnDYt2cRhnRJmeH87hq4Wn1FmEUh4VmW+EwREQb10sk",
	"CqfGHqgyCIgYTVQTZXtF0s5piqWa+4qYmMM4ptconAekCfYbmiSUgA9GMp+engDZB0c4gDqEUCCrEzmc",
	"x/MA+h0va2AtqvKWNrU5aVYOLFfiHfoXazi5jk/H7421MPmvp9OXeXZKbWnds16itX/SN+V8cldShq/k",
	"0i7RukiNsSbvmK/uGVVx6cBBE0Andxin7C2jWeoIM4dxM+Wuc6MjzLiYxzTQWsbVRXqjKNxsWKGj766m",
	"Gdl8wEawRI0+LNfcWEgBtjWhE6lFtpArZc9j61XskgjGvBEeKTSJ8sK1BJBuk+peEfGme1ObGLOyVJe9",
	"5qPSzNZGpPTmMimglFTmWua41LsXhCiGV9ShzfTvRX5hgaua2efixNzFdyZImtxMdwKmMwIAOb+mLPSO",
	"WDSoDrl/8PRZH0s0jzC4x5YfrXH396fPXN5smgcUWlNqVaPSVCn8kbZOtusiGdXSaK1nTHk72adn3mrv",
	"7FRtdWyW/Nt5XAr5Zf8kkDPIL8sUkOEg4y5bz6xNfmysj1Eqemb9zR0RajNllYXzf7VIoRbDx0og9hs+",
	"utWon/Vjo9w3X2FBuvJfupNYtEHEVdxPmkTXjLpsz5zmeQFMJ82XpHIH+mUojXEAPXRcSwttRs1MVrWx",
	"tuO1ndmNXDJxw3zSnLJsQJy0I93y1gxThhJ6heYJ0ufQvTWJ7qfiysqUXUCuLKGQXhPjD+U/u0P3MELz",
	"hIZoLnCC5mEeI216RzhBIP8s1YrsmcedLbk95U6JU6Krl3yoMZuWWUwoIB2wQX5p0gtlgzH4xFCEGPj8",
	"y5v9/f2XoxhfIh395CbwjhP0ByXSBo84EuCni79NXxxOpxeAMiD/nk4vnozBCVrCYG33pJkoO0NmfIOU",
	"IYFCifbCCc0bjSvY2ZtOn42ms9F072z29HB6cDh9qiful31+KmjaSkV3R7OEm2aiNyFcQ6xdKb0FNK1S",
	"w1Pec2WVlIqm3ZwlaU/ZYyUsb5DL11sMxhSGPSGxztqtc1gH5eZpBi1M0yU3/XGHLi18qhoaF6Lnyk7X",
	"JChXphIF3CuTn4CCzaYKdXQ2dHkdDHEaX6FwrpwGGlzOPWf8rZI/v0vjRI378NovznNUmnU6pXuJjpaw",
	"o1y1J6lCh2T0uI7FLiQmMFlKrLimsA8Cr1c4WBUxOsxB3nmj0ILiN0znvmyJlqTS2/VqRF57xkgdZkqA",
	"iJiL3nkq5hBsvkArTEIr7Ninb+EkOxSr/Na6okoL/4o0NtFVft+2B1zmTkBvHFiMt2Q0S9uITDeo0ZnU",
	"hBkZ5aPYtNYqRyrRks6Igo0Ie5GVXR/2C4xWt8e5GXXGc+HJCmHYXOwjqwZ7uFnNJWRUJsldw66+7Lem",
	"BDgzSTJNoe4TXxGOJZpZpmMvMAyx7AXjT5XWXfroNSYndPmLGuyzHMtlLiCygiRAc31Rep7nPa4gWaLO",
	"tBjLetbuHuBZKp1CdXqqsiz0/eswjEEaZ0tM+tyPxktCGZqr83hJMwX6a3ewVTOQMmRO7lUz525dIcZ1",
	"nKxzu1R+mUZD9UAuTEbKp6gjweEfqOVzQVmeqOI92yoH9aab+c0cmxr5pdsTpmQeZsrzE47RVvRabt4K",
	"klCHoaMYB9IAV3m0kjqyRJ8tp7GO2ud3RDTyLf6ypLGURcoTcp8MXcO1OnOiVIosKJBUt9ZkKeLcpOYM",
	"hoMyT8c9mTY3+kWQlJWmOlhhpNtEcLrSliV8gZiXsM/rSOnplOZspcZr5Cw1nEYfR+m820TniheCpU5Z",
	"cibTBqg2w/556EqommT0mrCphck32Cud1X4EBXwtve48NuYmrRzyHCeGmqIsjuVCSMBQgohOE4fqN6kw",
	"BtoRkbRVspP+3BQVxhP1cKVy55SnCt5FgCZYSE6iDKAkFeuhClWrczKHwCj6Vtj6FcdQqnayXEHc1wAv",
	"UdQh3WvCob4/TqqpM5xbvzp0j+vgSyAlIOXAHECRJwPE6ArFDd1olIIyWhwuqPw59488+qLSprLZIEzi",
	"PrrBwGCuAzSTM1MoBGIqLUrrcD8wvuYlXP99xFQMoPuwyLkDv2RxbPhRCjvfXXgrDCU5peB/SUXNWCgk",
	"MF7/4WIAqg4xGY11Gh3PEjlkulpzHMAY4CQ/Pyg0iiFcLeGldSP/jKIqJ1rfGnjIJ3ok0NAkZYjz0eXV",
	"KIWY8XawTGtweQVUazd8jlkIx1wgEqxbx8/1LCbGv1CH8zqVkTIplyJ1cbMYDUDOMyaFRZU5MkFdcMjh",
	"3Lkfp4IyuES1TDpFW3pZ43NyTj5QgfjhORmB31aIgAv9SYmtCwmm+WGEiaAXQ1NrJ+MCLBCASvmhUFlY",
	"cqpfP78DP8lZDNxDcMH3DyeTRRZcIjFJGYrw7xdPxnK6EyoRHOEY8TUXKJFMuOL17hO5vsl4PNZhzPEk",
	"R9tcfrh4otw0hiS/5WnG7UsY1/JcKuM5EYz55fxrRvMgdsXixPwSqG8Ktw6yLmZ6MX3rGl1PPxcrhmBY",
	"Tdc9qFsjaut0B0mkASXGV3UHLUosNAF/pz4qDV0IHCdRVHAHQoq4zro03kXhQk9AksUCj0wITwmt2l7q",
	"zZFfxqUNpjaIIzFU21tRaWPrXxeKnyAmXM+TxvlRB9fUVIXTSBEOLnL2uJCy/W4ke07+P4xxaBJpII4z",
	"OcNP1ZhrAtdyGoZExggKnziQ+LcCaxMbZ4fgfGC103vjRfj5wDVwrHiqXLRzzAI5VUycDywxHNOlJGSp",
	"dgxND4b2SFVpXLZu0LehQhd9z545CVz36EHgts00z0HoEsV5D7mHKvCR6ZC/pM0EIVE0QIDRa67Y2ozt",
	"UlZ+Z8w61S1atfqE8wLT21iDX+MSbesmkGQwrkJuPjXTE8J5Z5Gr1FnhiUl7d15sbK47fRcUrIWrnsDq",
	"2aqnq8HQW2QnqIxjT666/ij1qo5NdYn+8UR2cWdT+ozGdyRgmxmNll/lsRklIc4XUATVa1az5u0Meyy+",
	"JsGKUYL/KKZSYwD0Owo05UkT+msGicBqKvfVijTuKQXqC+khCooT326X/rfSpb9EKC2PfPMkKRBmyhmy",
	"wTBH9nKI8TlRhpIeHBy9VyKfCyx1s44RYAEEkmQAGY7X5XhYYBgXaGT2lTWGAnqF2Hp8Ti48x9cXQMBL",
	"xFWUDYWIBPkBX34BQjpu5anx2H11ykls1avrbp+6dEfUxfkGcRllXcbrOhNjTQ+RZ7ZZQTTf/WflFW8w",
	"henRdwp3PoSZrwZwHZzaZD533B/tLuKJrbFuftk71F3G15qHz7UDmnKG6X4UTPee7Y/2XgTPR7MZej6C",
	"z57uj54F08WLg/Dpy2h/ejgbPZ8ezA729ofTpwfPD8L9wGr+Yv/p3mhvuh8u9g6eheF+eDgbzZ5PnRUF",
	"q9c+rAqB6kN5/8bXM6VVBB04hcN2UnVakmd8m1+JeHpAGTEUQ+nLtN/vk6ZSERAKzB53RfHqkYgbHY3b",
	"eJy6cqpGf71Irq+od0jTouSuAzUbDu825HkEuQl0KmiaqphDeVHhF3MrfjAcfIIZr6TxlnToDLj6L9no",
	"yK6gduTRjvPyngdRNbNZfVQD5ITskB3yc78cvX6VDF1LtwrnFLpk0zHyAir9ix22QHI3JrMPnzwHk0Nw",
	"jeMwgCzMXbTqqdJi9PMd02AaeZa+9BhRpog3TxN6wCqcsLbmCFq6Tyk9z2b4DIuSC+5zQxo+c75qXtua",
	"2S2x2HMCn4nhod/KAUsLqsqjinZcPaqM9+1kuN/KtUOcmxzAfodep6bD9jK6nTncBT6/tFLMabkcd3aC",
	"0wk6clCTQQxIIYMJEojpwIHPDQIfTXEHHRLWF9N0iQ0Yx9ov4moUlUiTLhkMUTgECxRIdQpoHCIGTDoA",
	"ByaFACu/pWbqUIbwkuh7SuoQobkHuVdn2qoLVLqtmr6na2edFirPLuOIg/PB9HwwBmcrHahUrn8AieT/",
	"BQL6BC8EYsVotlxpByzTFTPGVpRF2r8zhwnhlQcoSaVE9KbFSnfxmmGx2Sl20UsDKswsxR/d9TbKeb90",
	"gu6riBNBHKtqrvyyedzfkvPvLHtTKNHues+52ioHda2hYQ5lQYA494C72Q2y5ljDJjZcQOkiLPdagrq/",
	"gaUnf+Bq0rWaqm0ZsS0es//yQ3Ojyxm91TZMWQ0OcntFUHMhg7eVru7K573FZY2u6xm1hw3uv+SWtzT/",
	"Vmtu3agzMyFVbXxEA4cqOHoPPqaIvPr0Dhx9fCMVKosHh4OuqvIjqQhH2hnDlJgi89pFjqgicSzUwhsT",
	"5Dlth4NnEoEqsJ8iAlM8OBzsq5+kPhcrBe0EpnhyNZuYSoOTfHhjIRdFgN+Faq5Xn95VC+mq1FAtWdV4",
	"e9OpuqZdXjGGaaHSJv/h2jgoLefWV0DcJXsV1mtGjxZkahN5liSQrQeHcg2gKNlLIgp4FqwA5KBSx1fA",
	"Jbdq7Cq3Ic18q9fCp44AxYavabi+t7U3KwI3Fm2mBQs5780j3gdtgFS2YuxE/M2wQY/GbOtLkmX944ch",
	"TEe95Ta0DAcH9whGo4a3Y2qtzlsYw3ryJVdcm2zM5Jv+Q8UBbrT8i5G2Ax079TGKYkyQRtsHnYxWmviD",
	"w383svcs8PJokipUCMVqkCuCgQXDwBbjOu/RFaL3v6z0pUE4Bw4v65HtKNV4rT3g02sjc4OhJ4eVxbkf",
	"hsMcxcB3jMOsh4c24jCzMZNvxgrbiMOM9diDw2zw/BxmwfB9c1j1GanWjQyTcQ6ck7PeInFEg/97+vGD",
	"h5WqYMmxigozTXILaQDUdCVUIQ1qEBkbtQWcf569P+kFjmzYAc5K6PxZHzgmZ6pT9JQl9buIWfJXXmlE",
	"3UMuLu8rmv6aIba2iBqL1bxo4SBid978zdDxnODaZFmpnBgd4RmZ+oH5JXgXCJWyeZvA8GW70tfxioGD",
	"U+zSTnH+1kiNDupNSnrIfXzlo3Hf/tvPXW3L2Ha8qLW5wT27N3iKmMij13O6ZDuAJMzTTSAg6NreddeG",
	"N2XA5Jt1ntSt5Y7Ux4IoWmXCMqYLVcg1I/hrVq1H5ld41eOtXgrPWw+mKTAiqiuL0DSHBMbcFE3NK+Kp",
	"gI5JnXKJDjXGHWXGDiheTQcAdtHUsI8O2UVaeRidtk190iLPiiP6AyctGsxTASL1TGdTv7QRRFcYZ2do",
	"4st29J4rjH9TDYRKcG/+HNJ4ZHLIRLHgXXXbJNQPU6oguN/sMc9X7haJdvkMj063aCTfw6aWJRFb9lS/",
	"5vhjS7e5pYUZetcdVS7ZZsz6Oa+M/n2qE9eLuzdGn+yqZChLU0cZ0Y8b5DUs7ofANhAc3zl5Od7C3VXq",
	"MkJq68RVFF1toa3yVY/vl7SaL5v0N4MfN6UpCqg8yLA5LRkgeoZpdfn6PsHaLZCOv/jrdh3casn+HTmg",
	"yuvb6nRlX3C2L3lMvuk/ygheD2JRudmPj1aGLSndnunLtfec3pnxvVUqrRY42y0i1Rnvt6fRonhkHwlW",
	"FHx+PNqw9e7Xg5wF1R743RHyUU9XVZ6CyV+3uKuFJRgkPNIp+C3m1Zlp9r3HGpvprH8VEysnhEJUUQD1",
	"S3w6V6CDuvQRT5dkyt837yQgZK5dP+Dpt7nxt1gXF76XvuPu/FtfhVVUT26b1cEf9WnrVbuHG4WnLZ25",
	"ZVHbeMbeQYQKybGpJv54BG0BVUnuOpu+z/H+mS57ur3Dffu6wJ95tO96o3mHzvmLF4qrO1wXZ5OAkivE",
	"8szdtu3XDbe5/zkoHSSAI03DmANM0kzom2RGluoXzvJV6fctIL80taH061iUgSscIHWLDG6ViGpL2h0y",
	"OlMJUgrLxDwRYh4yoxGA9dfhGkgd96C8/O5YP5Wa3w57gHzWHRftxeW8O8n4s/Jm3zZ43dzp+vPEuw+A",
	"RyrPKzu7CXNNTGGpduGu6/o90L7X76huTgZ7W4Jnd+SzqXZ3e7L4piqOb5LDV6OOjbxju+i5wy0uYOnp",
	"FPuqpe903pz/ZnVdgPdWlruzTdPvTrA39XXblnsT5Mo71j82fWdS0/rue0N+305qP1aKaEu2VjCgK0QA",
	"jtRjZIBni9ztY0W5rftJtx5+66j2aJXRKasvcpVNzxDPEl2/kej75erBEBUPVoUW1SblT2yrMsbn5GP9",
	"HYijo5OyG+YAxtdwzc2ThuH4nEhqA2pl/1CLAOomC4wZguF6lCKm6oCHdnFILiR1SXQhATFB4d8NLJSU",
	"tYiiOOMrBZqyC4Q1wPicnOZp7grzcrnXEJePw6idKkhPvwkiES0QWKCIMlQuHguNDedMRWXwHFKJorxO",
	"jNwA9RikWvjda8Vk5JLQawIU1Vhla8Yecirmr5BUvXTKXzuj3x1M6mGJ7IzoeYBw/J+hAGtxigNf/dCW",
	"vH3/7ndl7T9mAthqov7dYtjT7z2GXSTw94xhW1aR5wg4r1SaVyHuE3GsVDfmOyPIHjz/xnmMp98pMu/j",
	"DHx5NT/3H1E/ZdQ+oGrz88OnXTSpZeeSL9RxsJ3AI209zS3mB0YzYa474srd9dtzZe90xSJR8fVa4voV",
	"CW+XpPGdMOWPBMo2+nZnUd6ZijfMqizyKX+Q9I88z53lJWey5z2zkuy3iNGGUa9FjE4FywKRsR889dh4",
	"augvk+1DeU4BvXHuft1590+IKpzHLRLfNDjzg0N+cMjsz3GWqsS3+85SKxv6o2RFeOYHK248+ffCiPcf",
	"orSCgnU+/Gul+2uO21BttlutAnamUp3KNt9h5LtY965f+VabfMvgc7/La+a2xC2urj0GYV9Uzd/16xs7",
	"ek/O3NzR1LMZddK0U3jR9LuUXXrZuy+6aOqXXOoVI3aV72j1fYM1zcYhTSAm6nWDgUS1GcAtCwZdDyqE",
	"NOj9ioJ5NmHyNcPB5UhJ4JHOfB6VhecqMmbgsszUsrcL1TUWq1GYWPCoaZvQ5IWGi3b5Dzdfbv4nAAD/",
	"/xhU5Uo4yAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
