// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: error.proto

package pb

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_None ErrorCode = 0
	// This master is not leader right now.
	ErrorCode_MasterNotLeader ErrorCode = 1
	// Executor has been removed so it can't be recognized.
	ErrorCode_UnknownExecutor ErrorCode = 2
	// no enough resource can be used.
	ErrorCode_NotEnoughResource ErrorCode = 3
	// submit subjob failed
	ErrorCode_SubJobSubmitFailed ErrorCode = 4
	// TombstoneExecuto
	ErrorCode_TombstoneExecutor ErrorCode = 5
	//
	ErrorCode_SubJobBuildFailed ErrorCode = 6
	// create gRPC connection failed
	ErrorCode_BuildGrpcConnFailed ErrorCode = 7
	// unknown or upsupported metastore type
	ErrorCode_InvalidMetaStoreType ErrorCode = 8
	ErrorCode_UnknownError         ErrorCode = 10001
)

var ErrorCode_name = map[int32]string{
	0:     "None",
	1:     "MasterNotLeader",
	2:     "UnknownExecutor",
	3:     "NotEnoughResource",
	4:     "SubJobSubmitFailed",
	5:     "TombstoneExecutor",
	6:     "SubJobBuildFailed",
	7:     "BuildGrpcConnFailed",
	8:     "InvalidMetaStoreType",
	10001: "UnknownError",
}

var ErrorCode_value = map[string]int32{
	"None":                 0,
	"MasterNotLeader":      1,
	"UnknownExecutor":      2,
	"NotEnoughResource":    3,
	"SubJobSubmitFailed":   4,
	"TombstoneExecutor":    5,
	"SubJobBuildFailed":    6,
	"BuildGrpcConnFailed":  7,
	"InvalidMetaStoreType": 8,
	"UnknownError":         10001,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0579b252106fcf4a, []int{0}
}

type Error struct {
	Code    ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=pb.ErrorCode" json:"code,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_0579b252106fcf4a, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Error.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return m.Size()
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_None
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*Error)(nil), "pb.Error")
}

func init() { proto.RegisterFile("error.proto", fileDescriptor_0579b252106fcf4a) }

var fileDescriptor_0579b252106fcf4a = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xcb, 0x52, 0xf2, 0x30,
	0x14, 0x80, 0x1b, 0x7e, 0xae, 0xe7, 0xf7, 0x12, 0x82, 0x97, 0xae, 0x3a, 0xe8, 0x8a, 0x71, 0xc1,
	0x42, 0xdf, 0x00, 0x44, 0x47, 0x47, 0xba, 0x00, 0x7c, 0x80, 0xa6, 0x39, 0x83, 0x1d, 0x21, 0xa7,
	0x93, 0x26, 0x5e, 0xde, 0x42, 0xdf, 0xca, 0x25, 0x4b, 0x97, 0x4e, 0x79, 0x11, 0xa7, 0x15, 0x58,
	0xe6, 0xfb, 0xbe, 0xc9, 0x9c, 0x73, 0xe0, 0x3f, 0x1a, 0x43, 0xa6, 0x9f, 0x1a, 0xb2, 0x24, 0x2a,
	0xa9, 0x3c, 0xbf, 0x86, 0xda, 0xa8, 0x40, 0xe2, 0x0c, 0xaa, 0x31, 0x29, 0xf4, 0x59, 0x97, 0xf5,
	0x0e, 0x2e, 0xf7, 0xfb, 0xa9, 0xec, 0x97, 0x62, 0x48, 0x0a, 0x27, 0xa5, 0x12, 0x3e, 0x34, 0x96,
	0x98, 0x65, 0xd1, 0x1c, 0xfd, 0x4a, 0x97, 0xf5, 0x5a, 0x93, 0xed, 0xf3, 0x22, 0x67, 0xd0, 0xda,
	0xd5, 0xa2, 0x09, 0xd5, 0x90, 0x34, 0x72, 0x4f, 0x74, 0xe0, 0x70, 0x1c, 0x65, 0x16, 0x4d, 0x48,
	0xf6, 0x01, 0x23, 0x85, 0x86, 0xb3, 0x02, 0x3e, 0xea, 0x67, 0x4d, 0xaf, 0x7a, 0xf4, 0x86, 0xb1,
	0xb3, 0x64, 0x78, 0x45, 0x1c, 0x43, 0x3b, 0x24, 0x3b, 0xd2, 0xe4, 0xe6, 0x4f, 0x13, 0xcc, 0xc8,
	0x99, 0x18, 0xf9, 0x3f, 0x71, 0x02, 0x62, 0xea, 0xe4, 0x3d, 0xc9, 0xa9, 0x93, 0xcb, 0xc4, 0xde,
	0x44, 0xc9, 0x02, 0x15, 0xaf, 0x16, 0xf9, 0x8c, 0x96, 0x32, 0xb3, 0xa4, 0x71, 0xf7, 0x4b, 0xad,
	0xc0, 0x7f, 0xf9, 0xc0, 0x25, 0x0b, 0xb5, 0xa9, 0xeb, 0xe2, 0x14, 0x3a, 0x25, 0xb8, 0x35, 0x69,
	0x3c, 0x24, 0xad, 0x37, 0xa2, 0x21, 0x7c, 0x38, 0xba, 0xd3, 0x2f, 0xd1, 0x22, 0x51, 0x63, 0xb4,
	0xd1, 0xd4, 0x92, 0xc1, 0xd9, 0x7b, 0x8a, 0xbc, 0x29, 0xda, 0xb0, 0xb7, 0x1d, 0xb2, 0xd8, 0x8b,
	0x7f, 0x86, 0x03, 0xff, 0x2b, 0x0f, 0xd8, 0x2a, 0x0f, 0xd8, 0x4f, 0x1e, 0xb0, 0x8f, 0x75, 0xe0,
	0xad, 0xd6, 0x81, 0xf7, 0xbd, 0x0e, 0x3c, 0x59, 0x2f, 0xef, 0x79, 0xf5, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x63, 0x05, 0xf5, 0x35, 0x5e, 0x01, 0x00, 0x00,
}

func (m *Error) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Error) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Error) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintError(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x12
	}
	if m.Code != 0 {
		i = encodeVarintError(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintError(dAtA []byte, offset int, v uint64) int {
	offset -= sovError(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Error) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovError(uint64(m.Code))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	return n
}

func sovError(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozError(x uint64) (n int) {
	return sovError(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Error) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowError
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Error: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Error: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= ErrorCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipError(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthError
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipError(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowError
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowError
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowError
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthError
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupError
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthError
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthError        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowError          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupError = fmt.Errorf("proto: unexpected end of group")
)
