@startuml Actor system poll sequence

Router -> Router : Send(msgs)

Router -> Router : find proc

Router -> Mailbox : proc\n  .Mailbox\n  .Send(msgs)

Router -> ready : schedule(proc)

ready -> ready : enqueue(proc)

ready -> System : signal()

System -> ready : fetchProc()

ready -> System : return proc

System -> Actor : poll proc.Actor

Actor -> Mailbox : tryReceive

Mailbox -> Actor : return msgs

Actor -> Actor : Poll(msgs)

@enduml
