@startuml
autonumber

Owner -> Processor_A: Announce
Owner -> Processor_B: Announce
Processor_A --> Owner: Sync
Processor_B --> Owner: Sync
note left
Owner waits for all
processors to Sync
before dispatching
any table
endnote

Owner -> Processor_A: DispatchTable(Table 1)
hnote over Processor_A
starts Table 1
endhnote

Owner -> Processor_B: DispatchTable(Table 2)
hnote over Processor_B
starts Table 2
endhnote

hnote over Processor_A
Table 1 ready
endhnote
Processor_A --> Owner: DispatchTableResponse(Table 1)
hnote over Processor_B
Table 2 ready
endhnote
Processor_B --> Owner: DispatchTableResponse(Table 2)

Processor_A --> Owner: Checkpoint
Processor_B --> Owner: Checkpoint

@enduml
