#!/bin/bash
# parameter 1: work directory
WORK_DIR=$1

set +e

## check data race
if [ ! -f $WORK_DIR/stdout.log ]; then
	exit 0
fi

# Check stdout.log, stdout$logsuffix.log, cdc_kafka_consumer_stdout$log_suffix.log
# cdc_storage_consumer_stdout.log
grep -q -E 'DATA RACE|panic:' $WORK_DIR/*out*.log

if [ $? -eq 0 ]; then
	cat $WORK_DIR/stdout.log
	exit 1
else
	exit 0
fi
