#!/bin/bash

# parameter 1: pd host
# parameter 2: pd port

set -eux

pd_host=${1}
pd_port=${2}

tso=$(run_cdc_cli tso query --pd=http://${pd_host}:${pd_port})
# make sure get tso only
# the tso got above is:
# "427768583921860609 PASS coverage: 2.7% of statements in github.com/pingcap/tiflow/..."
# and only "427768583921860609" is a real tso
echo $tso | awk -F " " '{print $1}'

set +x
