server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: kafka #rocketMQ
#  canalServerHost: localhost:11111
  zookeeperHosts: zookeeper:2181
  mqServers: kafka:9092 #or rocketmq
  flatMessage: false
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  username:
  password:
  vhost:
#  srcDataSources:
#    defaultDS:
#      url: jdbc:mysql://localhost:3306/mytest?useUnicode=true
#      username: root
#      password: 121212
  canalAdapters:
  - instance: testdb # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://downstream-tidb:4000/testdb
          jdbc.username: root
          jdbc.password:
