name: DM Web UI Lint

on:
  pull_request:
    paths:
      - 'dm/ui/**'

jobs:
  dm-web-ui-lint:
    name: DM Web UI Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dm/ui

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: 'dm/ui/yarn.lock'
      - name: Install dependencies
        run: yarn --ignore-scripts
      - name: Type check
        run: yarn type-check
      - name: Lint
        run: yarn lint
