name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  pull_request_review_comment:
    types: [created]


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Build
      run: docker build .
