name: CDC Integration Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'dm/**'
      - 'engine/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'dm/**'
      - 'engine/**'

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  MySQL-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - name: Check Docker Version
        run: docker --version

      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          docker volume prune -f
          docker image prune -f
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Pull images
        run: docker-compose -f ./deployments/ticdc/docker-compose/docker-compose-avro.yml pull --ignore-pull-failures

      - name: TiDB version
        run: |
          docker run pingcap/tidb:nightly -V
          docker run pingcap/tikv:nightly -V
          docker run pingcap/pd:nightly -V

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/tests/mq_protocol_tests
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/tests/mq_protocol_tests
          ./mq_protocol_tests -protocol=mysql

      - name: Clean Up
        if: ${{ always() }}
        run: |
          $GITHUB_WORKSPACE/scripts/avro-local-test.sh down

  Canal-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - name: Check Docker Version
        run: docker --version

      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          docker volume prune -f
          docker image prune -f
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Pull images
        run: docker-compose -f ./deployments/ticdc/docker-compose/docker-compose-canal.yml pull --ignore-pull-failures

      - name: TiDB version
        run: |
          docker run pingcap/tidb:nightly -V
          docker run pingcap/tikv:nightly -V
          docker run pingcap/pd:nightly -V

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/tests/mq_protocol_tests
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/tests/mq_protocol_tests
          ./mq_protocol_tests -protocol=canal

      - name: Clean Up
        if: ${{ always() }}
        run: |
          $GITHUB_WORKSPACE/scripts/canal/canal-local-test.sh down

  Avro-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - name: Check Docker Version
        run: docker --version

      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          docker volume prune -f
          docker image prune -f
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Pull images
        run: docker-compose -f ./deployments/ticdc/docker-compose/docker-compose-avro.yml pull --ignore-pull-failures

      - name: TiDB version
        run: |
          docker run pingcap/tidb:nightly -V
          docker run pingcap/tikv:nightly -V
          docker run pingcap/pd:nightly -V

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/tests/mq_protocol_tests
          go build
      
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/tests/mq_protocol_tests
          ./mq_protocol_tests

      - name: Clean Up
        if: ${{ always() }}
        run: |
          $GITHUB_WORKSPACE/scripts/avro-local-test.sh down
