addr = "0.0.0.0:10240"

etcd-endpoints = ["etcd-standalone:2379"]

[framework-metastore-conf]
endpoints = ["mysql-standalone:3306"]
schema = "test"
auth.user = "root"
auth.passwd = "123456"

[business-metastore-conf]
endpoints = ["mysql-standalone:3306"]
schema = "test"
auth.user = "root"
auth.passwd = "123456"
